GitHubにSSH接続する方法を追記
railsgirls-jp/railsgirls.jp pull request #546
Opened 2022-01-10 08:21 UTC by cobachie

パスワード認証が廃止されましたね
https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/

2022-02-05 03:09 UTC, cobachie commented
@emorima こちらもレビューお願いいたします〜 🙏

2022-03-27 01:51 UTC, emorima commented on _posts/2013-04-14-github.md
> +pbcopy < ~/.ssh/id_rsa.pub
`pbcopy` がMacのコマンドなので、Windows/WSLのケースでの記載が必要そうです！

2022-03-27 01:51 UTC, emorima commented on _posts/2013-04-14-github.md
> +pbcopy < ~/.ssh/id_rsa.pub
`ssh-keygen -t ed25519` で作成しているので、`~/.ssh/id_ed25519.pub` で作成されると思います！

2022-03-27 01:53 UTC, emorima commented on _posts/2013-04-14-github.md
> +pbcopy < ~/.ssh/id_rsa.pub
Windows版は `clip` らしいので、私の方で試してみてコメントに記載します〜！

2022-03-27 01:55 UTC, cobachie commented on _posts/2013-04-14-github.md
> +pbcopy < ~/.ssh/id_rsa.pub
Windows の場合はどのコマンド使うといいでしょ？

https://docs.github.com/ja/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account
の `clip` でいいですかねー 👀

2022-04-02 02:27 UTC, cobachie commented on _posts/2013-04-14-github.md
> +pbcopy < ~/.ssh/id_rsa.pub
- `rsa` -> `ed25519` に修正
- Windows のクリップボードにコピーする方法を追記（ `clip` で記載しています）

@emorima ご確認お願いいたします！

2022-05-15 13:57 UTC, emorima requested changes
@cobachie 

Windowsで試したところ、ターミナル (コマンドプロンプト)では、コマンドが使えなかったので修正お願いします！

2022-05-15 13:57 UTC, emorima commented on _posts/2013-04-14-github.md
> +
Windows の場合、ターミナル(コマンドプロンプト)では `ls`、`clip`、`ssh-keygen` コマンドが使えませんでした。

Windowsの場合、ssh keyを作るところまでは、Gitをインストールすると一緒にインストールされる `Git Bash` を使う必要があるため、
「Windowsの場合、 Git Bashを開いて実行してください」の記載をお願いします。

2022-05-16 12:25 UTC, cobachie commented on _posts/2013-04-14-github.md
> +
ありがとうございます！追記しました。ご確認お願いします〜 🙏  @emorima

2022-05-16 22:43 UTC, emorima approved these changes

2022-05-16 22:44 UTC, merged