WIP: Replace GitHub pages gem with GitHub actions to use Ruby 3.2
railsgirls-jp/railsgirls.jp pull request #596
Opened 2023-03-08 04:44 UTC by yasulab

[github-pages gem](https://pages.github.com/versions/) を使っている場合、現時点では Ruby 2.7 + Jekyll 3.9 以下に固定されちゃうと思うので、差し支えなければ GitHub Actions でちょっとイイ感じにしてみようと思います 🛠💨

関連 PR:

- #595 

## Before → After のイメージ
引用元: https://speakerdeck.com/yasslab/mitou-junior-on-jekyll?slide=51

![Before](https://user-images.githubusercontent.com/155807/223606540-0ff3fa75-6c56-4f9d-a4ae-8020481d66db.png) ![After](https://user-images.githubusercontent.com/155807/223606618-23cbb2ee-1bff-4cf6-8e6a-e8c673be5698.png)

2023-03-09 02:16 UTC, hsbt requested changes

2023-03-09 02:16 UTC, hsbt commented on .github/workflows/test_and_deploy.yml
> +    - name: 🧪 Install gems
`ruby/setup-ruby` で `bundler-cache` を有効にしている場合は `bundle install` は自動実行されるので不要です。

2023-03-09 02:16 UTC, hsbt commented on .github/workflows/test_and_deploy.yml
> +      uses: peaceiris/actions-gh-pages@v3
https://github.com/rubima/magazine.rubyist.net/blob/master/.github/workflows/jekyll.yml#L36 のように `actions/upload-pages-artifact@v1` した上で `deploy` jobs を分けて `actions/deploy-pages@v1` を使う方法にしてもらえますか? できるだけ公式の actions を使いたいなあという意図があります 🙏

2023-03-10 02:11 UTC, yasulab commented on .github/workflows/test_and_deploy.yml
> +    - name: 🧪 Install gems
早速のレビューありがとうございます! こちら 2b70e12 で対応しました! 🛠💨✨

2023-03-10 02:46 UTC, yasulab commented on .github/workflows/test_and_deploy.yml
> +      uses: peaceiris/actions-gh-pages@v3
@hsbt コメントありがとうございます...!! 🙏 ✨  いただいた Workflow を参考に書き直してみました! 🛠💨 10714fc

📝 NOTE: `rake test` の結果で `deploy` job を止めるかどうかは悩んだんですが、内部リンクが多少壊れていても大枠では問題ないと判断し、一旦は `rake test` で failed になっても気にせず `deploy` する方向に寄せています! 🚀✨

2023-03-10 02:47 UTC, yasulab commented
あ、deploy flow で落ちてる...? 😂 https://github.com/railsgirls-jp/railsgirls-jp.github.io/actions/runs/4380802295/jobs/7668255770

2023-03-10 04:10 UTC, hsbt commented
まだ repo の設定を変えてないだけなので一旦マージしてから様子を見てみますね。

🚀

2023-03-10 04:10 UTC, hsbt approved these changes

2023-03-10 04:10 UTC, merged

2023-03-10 04:30 UTC, hsbt commented
なんか動いてそう

2023-03-10 06:55 UTC, yasulab commented
@hsbt マージありがとうございます!! (＞人＜ )✨

> なんか動いてそう

るびま と同じ仕組みになったので多分設定不要になったかもです 😂
記録のため Description にも追記しておきました! 📝 💨