Cosmetic changes to README.md
railsgirls-jp/railsgirls.jp pull request #678
Opened 2023-05-16 23:17 UTC by cafedomancer

Markdown 中の整っていなそうな箇所を整えました。また、以下の変更も合わせて加えています。

- `_post` -> `_posts`
- code block -> code quote
- コマンドには `$` を付ける
- year-month-date -> YYYY-MM-DD

2023-05-22 15:15 UTC, urimaro requested changes
ありがとうございます！
READMEには気が回っていませんでした

1つ気になることがあります
`rake` を使ったコマンドが3箇所あると思います
こちらは `bundle exec` をつけないと実行できないのではないかと思いました

お手数ですが、合わせて確認していただけませんか？

2023-05-30 12:02 UTC, cafedomancer commented
> 1つ気になることがあります `rake` を使ったコマンドが3箇所あると思います こちらは `bundle exec` をつけないと実行できないのではないかと思いました

`bundle exec` がなくても動作することは確認していますが、`Gemfile` に指定したものを使うようにするにはあったほうがよいと思うので、`bundle exec` を追加します。

2023-05-31 00:26 UTC, urimaro commented
> bundle exec がなくても動作することは確認していますが、

私の環境では動作しなかったのですが、環境の構築の仕方が良くなかったかもしれませんね💦
失礼しました

2023-05-31 00:27 UTC, urimaro approved these changes
対応していただき、ありがとうございました！
LGTM:+1:です

2023-05-31 00:28 UTC, merged