Translate main_guides.md
railsgirls-jp/railsgirls.jp pull request #680
Opened 2023-05-17 06:38 UTC by cafedomancer

Close #679

2023-05-22 23:33 UTC, urimaro requested changes
翻訳にご協力いただき、ありがとうございます！
2点、コメントしましたので、ご確認ください🙏

2023-05-22 23:33 UTC, urimaro commented on _includes/main_guides.md
> +* ガイド 11: [Style the idea pages using HTML and CSS](/design) {% if page.permalink == 'design' %}(このページです！){% endif %}
せっかくなので、こちらも訳していただけますか？🙏

2023-05-22 23:33 UTC, urimaro commented on _includes/main_guides.md
> +* ガイド 14: [Test your app with RSpec](/testing-rspec) {% if page.permalink == 'testing-rspec' %}(このページです！){% endif %}
せっかくなので、こちらも訳していただけますか？🙏

2023-05-30 11:56 UTC, cafedomancer commented on _includes/main_guides.md
> +* ガイド 11: [Style the idea pages using HTML and CSS](/design) {% if page.permalink == 'design' %}(このページです！){% endif %}
未翻訳だと思っていたのですが、タイトルのみ翻訳されているようですね。対応します。

2023-05-30 11:58 UTC, cafedomancer commented on _includes/main_guides.md
> +* ガイド 14: [Test your app with RSpec](/testing-rspec) {% if page.permalink == 'testing-rspec' %}(このページです！){% endif %}
このページは未翻訳で、この PR でタイトルを翻訳してしまうと、リンク先のページとの整合性を保つ必要が出てきます。コードベース中の "Test your app with RSpec" というタイトルすべてを翻訳する変更は、この PR に含めるべきではないと思うので、この PR では未翻訳のままにしておきたいです。

2023-05-31 00:30 UTC, urimaro commented on _includes/main_guides.md
> +* ガイド 14: [Test your app with RSpec](/testing-rspec) {% if page.permalink == 'testing-rspec' %}(このページです！){% endif %}
なるほど
ごもっともだと思います
現状のままで結構です

2023-05-31 00:32 UTC, urimaro reviewed
対応いただき、ありがとうございました！
LGTM:+1:です

2023-05-31 00:33 UTC, urimaro approved these changes

2023-05-31 00:33 UTC, merged