improve translations and capitalize some words
railsgirls-jp/railsgirls.jp pull request #684
Opened 2023-05-17 10:53 UTC by hoshico

## やったこと

- ドットインストールの説明の中での言語やライブラリの表記を修正した。
* Twitter Bootstrapは、Bootstrapの方が一般的かと思いました。(ドットインストール内でもBootstrapの表記)

- 「実際に何かを作ってみる」の翻訳を少し修正いたしました。

2023-05-22 23:30 UTC, urimaro requested changes

2023-05-22 23:30 UTC, urimaro commented on _pages/how-to-continue-with-programming.md
> +それを解決するアプリケーションを作成し、苦痛から解放されましょう。この方法はチュートリアルをやるよりも、やる気が高まる方法です。同時に、あなたの友達や世界中のみんなにあなたのアプリケーションを見せるということも忘れてはいけません。フィードバックを聞いたり、学ぶことを続けましょう。
> 苦痛から解放されましょう。

少し違和感を感じました
原文は `try to solve` なので解決しようと挑戦するようなニュアンスがあると思いました
例えば以下のような訳はいかがでしょうか？

- アプリケーションを作成してイライラすることを解決してみましょう

2023-05-22 23:30 UTC, urimaro commented on _pages/how-to-continue-with-programming.md
> +それでもまだ何を作って良いのかわからないなら、私に良いアイデアがあります。是非、あなたの国や街の RailsGirls サイトを作ってみて下さい。もし、スイスに住んでいるなら私達が作った [railsgirls.ch](http://railsgirls.ch/) というサイトを見てください。
> もし、スイスに住んでいるなら私達が作った [railsgirls.ch](http://railsgirls.ch/) というサイトを見てください。

現在の [原文](https://github.com/railsgirls/guides.railsgirls.com/blob/main/_pages/how-to-continue-with-programming.md) には該当する箇所が見つかりませんでした
翻訳を改善するときに、どちらの英文を参考にしましたか？

2023-05-22 23:31 UTC, urimaro commented
改善案を提案していただき、ありがとうございます！
2点コメントしました
ご確認ください

2023-05-23 10:55 UTC, hoshico commented on _pages/how-to-continue-with-programming.md
> +それを解決するアプリケーションを作成し、苦痛から解放されましょう。この方法はチュートリアルをやるよりも、やる気が高まる方法です。同時に、あなたの友達や世界中のみんなにあなたのアプリケーションを見せるということも忘れてはいけません。フィードバックを聞いたり、学ぶことを続けましょう。
@urimaro 
ご確認ありがとうございます。
ご指摘いただき確かに違和感感じましたので修正加えさせていただきました。

2023-05-23 10:58 UTC, hoshico commented on _pages/how-to-continue-with-programming.md
> +それでもまだ何を作って良いのかわからないなら、私に良いアイデアがあります。是非、あなたの国や街の RailsGirls サイトを作ってみて下さい。もし、スイスに住んでいるなら私達が作った [railsgirls.ch](http://railsgirls.ch/) というサイトを見てください。
@urimaro 

こちら私が手をつけた際にはあった気がするのですが、今は無くなっているようです。
うろ覚えですいません。
削除させていただきました。

2023-05-24 00:14 UTC, urimaro approved these changes
変更点を確認しました
LGTM:+1:です！

2023-05-24 01:47 UTC, merged

2023-05-24 01:55 UTC, maimux2x commented
本番にマージしたため、該当ページのご確認とissueのcloseをお願いいたします〜🙏