「Write a little game in Ruby!」を翻訳
railsgirls-jp/railsgirls.jp pull request #685
Opened 2023-05-18 14:21 UTC by YuyaYoshioka

「Write a little game in Ruby!」を翻訳しました。

fix https://github.com/railsgirls-jp/railsgirls.jp/issues/676

2023-05-18 14:24 UTC, YuyaYoshioka commented
<img width="1438" alt="image" src="https://github.com/railsgirls-jp/railsgirls.jp/assets/71418423/de4a5353-a356-402c-a62e-832344af8406">

![screencapture-localhost-4000-ruby-game-2023-05-18-23_23_27](https://github.com/railsgirls-jp/railsgirls.jp/assets/71418423/1cf52a05-a0e4-4b3b-82c9-7690f9976afd)

2023-05-23 00:18 UTC, urimaro requested changes
翻訳にご協力いただき、ありがとうございます！
いくつかコメントしましたので、確認をお願いします:pray:

2023-05-23 00:18 UTC, urimaro commented on _pages/ruby-game.md
> +[gosu](http://www.libgosu.org/)は2Dゲームを開発するためのライブラリです。Gosuは2Dグラフィックスやテキスト（３Dハードウェアによる高速化），音源のサンプルや音楽，キーボード，マウス，ゲームパッド/ジョイスティックの入力に対して，使いやすくゲームに適したインタフェースを提供しているという特徴があります。また，RMagick，Chipmunk，OpenGLとの統
全体の話ですが、原文の `,` は `、` に置き換えてください:pray:
このようなルールにできることは、まとめてみます:bow:

> OpenGLとの統合のデモ

「OpenGLと統合されたデモ」「OpenGLと一体化したデモ」といった表現のほうが自然かなと思いました

2023-05-23 00:18 UTC, urimaro commented on _pages/ruby-game.md
> +そして `ruby CptnRuby.rb`または`ruby RMagickIntegration.rb`または`ruby Tutorial.rb`を実行してください。
比較しやすくするために、改行を原文とそろえてください:pray:

2023-05-23 00:18 UTC, urimaro commented on _pages/ruby-game.md
> +次のコマンドを実行しましょう。
リポジトリをコピーする説明が抜けてしまっているようです

2023-05-23 00:18 UTC, urimaro commented on _pages/ruby-game.md
> +このGameクラスの中に書かれている`def`はメソッドです。ここでは，どのようにプログラムの処理が行われるべきか定義(**def**ine)しています。次のスニペットを見てください。
> どのようにプログラムの処理が行われるべきか

「プログラムにやってもらうことを定義する」ことを説明しているのだと思いました
なので「プログラムがどの処理を行うべきか」「プログラムに何を処理させるべきか」といった表現の方が自然かなと思いました
個人的な意見なので、採用するかどうかはおまかせします

2023-05-23 00:18 UTC, urimaro commented on _pages/ruby-game.md
> +`Game.new.show`がわかりますか？これは新しいインスタンスを作ります。メモリがなくなり，ゲームが動かなくなった時は新しいゲームを始めてください。楽しんでください！
「And see the `Game.new.show`?」は `Game.new.show` を探してほしいんだろうなと思いました
見つけられたかどうかをたずねる表現のほうが自然かもしれません
個人的な意見なので、採用するかどうかはおまかせします

2023-05-23 01:15 UTC, urimaro commented on _pages/ruby-game.md
> +ここでは，必要なgemを'呼び出している'ことを確認しましょう。それでは，`class`（もしくは多重クラス）に移動しましょう。
`multiple classes` は「多重クラス」という言葉に該当するのでしょうか？
(多重クラスがどのようなクラスなのかもわかっておらず…)
もしかしたら、単純に複数のクラスを意味しているのかもしれないと思いました

2023-07-26 05:03 UTC, maimux2x commented
@YuyaYoshioka 
こんにちは！
ドキュメントの翻訳にご協力くださり、ありがとうございます🙏✨
こちらのPRがレビュー中のようでしたため、コメントいたしました。

もし可能であればレビュー内容をご確認いただき、修正をあげていただければと思うのですが、いかがでしょうか？
直近でご対応が難しい場合は自分の方で修正を反映させるため、無理に対応はいただかなくて大丈夫です！

ご確認のほどよろしくお願いいたします😊

2023-10-11 12:11 UTC, maimux2x commented
こちらコメントから一定期間が経過しているため、PRをCloseさせていただきます🙇🏻‍♀️

2023-10-11 12:11 UTC, closed without merging

2023-10-11 12:14 UTC, maimux2x commented
レビューコメントの内容を確認し、自分の方でPR上げ直します！