Transrate commenting.md
railsgirls-jp/railsgirls.jp pull request #689
Opened 2023-05-20 10:39 UTC by yukyu30

## 概要
fix: https://github.com/railsgirls-jp/railsgirls.jp/issues/675
「Rails Girls アプリのコメント機能」のページを翻訳しました

### 変更後の文章
![127 0 0 1_4000_commenting (1)](https://github.com/railsgirls-jp/railsgirls.jp/assets/61819079/1b3113dc-48f4-4b98-9970-d18e63fe9dc7)

2023-05-20 13:58 UTC, yukyu30 commented on _pages/commenting.md
> +commentは、`Idea`モデルを参照する`belongs_to :idea`という行によって、文字通り「ideaに属している」ことをすでに認識しています。これは、先ほどのマイグレーションで自動的に追加されました。
https://github.com/railsgirls/guides.railsgirls.com/blob/45f54b85ff1764330e2df85a535338d3eb0e5d34/_pages/commenting.md?plain=1#L64-L72
ここは最新版のドキュメントに合わせて変更しました

2023-05-20 13:58 UTC, yukyu30 commented on _pages/commenting.md
> +`app/views/ideas/show.html.erb` を開いて、最後の行に次のコードを追加します。
https://github.com/railsgirls/guides.railsgirls.com/blob/45f54b85ff1764330e2df85a535338d3eb0e5d34/_pages/commenting.md?plain=1#L154-L156C1

最新版のドキュメントに合わせて修正、翻訳しました

2023-05-24 22:24 UTC, urimaro requested changes
翻訳にご協力いただき、ありがとうございます！
いくつかコメントしましたので、確認をお願いします:pray:

2023-05-24 22:24 UTC, urimaro commented on _pages/commenting.md
> +まず、comments routeを追加をします。comment routeはideas routesの下にネストされるため、routeからcommentがどのideasに紐づくかを特定できるようになります。
原文と比較しやすくするため、改行位置や空行を原文とそろえてください:pray:
ここ以外の部分もそろえていただけると助かります

---

> comments routeを…
> routeから…

この場合の `route` は「ルーティング」で良いと思います
(Railsガイドにならいました)

たとえば以下の部分は「コメントのための新しいルーティング」といった訳はいかがでしょうか

> a new route for the comments

---

以下の部分が抜けてしまっているようです

> Open the `config/routes.rb` file. Change the following line:

2023-05-24 22:24 UTC, urimaro commented on _pages/commenting.md
> +## Commentモデルの作成
他のページにならって、見出しは「〜しよう」のように呼びかける表現にすると親しみやすくなると思っています
いかがでしょうか
(翻訳の方針のようなものを作ったほうが良いと思っていますが、まだまとめられていません:bow:)

2023-05-24 22:24 UTC, urimaro commented on _pages/commenting.md
> +新しいマイグレーションファイルが作成されました。以下のコマンドでマイグレーションを実行して、データベースにcommentsテーブルを作成します。
> 以下のコマンドでマイグレーションを実行して、データベースにcommentsテーブルを作成します。

意味としては訳していただいたとおりだと思いますが、原文を尊重したいので、2つの文に分けて訳していただけないでしょうか:pray:
もちろん、直訳が良いと思っているわけではないです

2023-05-24 22:24 UTC, urimaro commented on _pages/commenting.md
> +Railsはideasとcommentsの2つのオブジェクトの関係を知っている必要があります。その結果、特定のideaに関連するcommentsのみ取得できます。1つのideaは複数のcommentsが持つことができ、1つのcommentは1つのideaのみ持つことができます。
原文を参照しながら訳していただいて、ありがとうございます

> Railsはideasと…

原文は `Your app needs` で始まっているので、「アプリは」「あなたのアプリは」としてはいかがでしょうか

2023-05-24 22:24 UTC, urimaro commented on _pages/commenting.md
> +作成したファイルをテキストエディタで開き、空の状態にして、次のコードをコピーペーストします。
> 空の状態にして

この `should` は「〜のはずだ」というような意味かなと思いました
ですので「空っぽだと思いますが」「何もないと思いますが」といった訳はいかがでしょうか

2023-05-24 22:24 UTC, urimaro commented on _pages/commenting.md
> +コントローラがどのように動作し、HTTPリクエスト、モデル、ビューと相互作用するかを説明する。
> …説明する。

見出し同様、こちらも呼びかけるような表現にすると親しみやすくなると思います

2023-05-24 22:24 UTC, urimaro commented on _pages/commenting.md
> +フォームからデータを送信するためには、フォームのビューファイルを作成し、アプリに表示する必要があります。
> フォームのビューファイルを作成し、アプリに表示する必要があります。

`so that 〜` は「〜できるように」という意味かなと思いました
以下のような訳はいかがでしょうか

*  フォームを表示できるように ファイルを作成する必要があります。
*  フォームを表示するためにファイルを作成する必要があります。

2023-05-24 22:24 UTC, urimaro commented on _pages/commenting.md
> +ブラウザを更新すると、ideaの詳細ページにcommentを追加するためのフォームが表示されます。名前、メッセージを入力してください。そして、「コメントを作成する」ボタンをクリックします。すると、ページの上部に緑色で「Comment was successfully created.」と表示されるはずです。
> ブラウザを更新すると

ブラウザを新しくするわけではないので「再度読み込むと」といった感じのほうが良さそうに思いました

> 「コメントを作成する」ボタン

日本語で表示されるわけではないと思うので、原文のまま「Create comment」で良いと思います

2023-05-24 22:24 UTC, urimaro commented on _pages/commenting.md
> +おめでとうございます！あなたのアプリがcommentをサポートするようになりました！`Comment` というコメント用の新しいモデルを追加しました。このモデルは、commentsを保存するためにデータベースとやり取りします。新しい`CommentsController`は、commentsの作成と削除をモデルに指示します。ビューが更新されて、ideaごとのcommentsを表示し、フォームで新
> あなたのアプリがcommentをサポートするように…

このcommentは一般的な意味でのコメントだと思うので「コメント」のほうが良いと思います

この部分だけではありませんが、comment、comments、コメントの使い方があいまいかなと思いました
クラス名、モデル名は英語表記、一般的な意味で使っている場合はカタカナのほうが良いと思いました
ideaについても同様です
検討してみてください:pray:

2023-05-25 16:00 UTC, yukyu30 commented
レビューの取り込みを途中まで行いました。
comment、comments、コメントの使い方の部分については後日対応します!

2023-05-25 22:36 UTC, urimaro commented
> レビューの取り込みを途中まで行いました。 comment、comments、コメントの使い方の部分については後日対応します!

ありがとうございます
ガイド全体として、英語のままにする、カタカナにする、日本語にする基準が明確にできていないので、別のpull requestで対応することにしていただいても結構です

2023-05-27 06:04 UTC, yukyu30 commented
@urimaro 
comments, comment、コメントの使い分けを行いました！[c014cb1](https://github.com/railsgirls-jp/railsgirls.jp/pull/689/commits/c014cb1058f3362d07141fb03bd73f041861ffcc)
Railsガイドを参考に以下のようなルールで統一しました。
- ルーティングの場合は英語の単数系（例：commentルーティング）
- テーブルの場合は英語の複数形（例：commentsテーブル)
- 一般的な意味で使っている場合は日本語

レビューの取り込みを行ったのでもう一度ご確認いただきたいです 🙏

2023-05-27 23:03 UTC, urimaro commented
> Railsガイドを参考に以下のようなルールで統一しました。
>
> * ルーティングの場合は英語の単数系（例：commentルーティング）
> * テーブルの場合は英語の複数形（例：commentsテーブル)
> * 一般的な意味で使っている場合は日本語

ありがとうございます
確認しました！

2023-05-27 23:11 UTC, urimaro requested changes
対応、ありがとうございます
翻訳は良いと思います

最後に原文と比較しやすくするため、改行位置や空行を原文とそろえてください🙏

2023-05-28 03:05 UTC, yukyu30 commented on _pages/commenting.md
> +commentは、`Idea`モデルを参照する`belongs_to :idea`という行によって、文字通り「アイデアに属している」ことをすでに認識しています。これは、先ほどのマイグレーションで自動的に追加されました。
最新版の英語版のドキュメントに合わせため文章の構成が異なっています。

https://github.com/railsgirls/guides.railsgirls.com/blob/cfc7acf06805d0b1e04745a7dbfa7aa1b2c56aee/_pages/commenting.md?plain=1#L48-L72

2023-05-28 03:10 UTC, yukyu30 commented on _pages/commenting.md
> +`app/views/ideas/show.html.erb` を開いて、最後の行に次のコードを追加します。
こちらも英語版の原文に合わせたため構成が異なっています
https://github.com/railsgirls/guides.railsgirls.com/blob/cfc7acf06805d0b1e04745a7dbfa7aa1b2c56aee/_pages/commenting.md?plain=1#L152-L156

2023-05-28 03:18 UTC, yukyu30 commented
@urimaro 

> 最後に原文と比較しやすくするため、改行位置や空行を原文とそろえてください
対応できておらずすいませんでした！改行などを追加して原文と揃えました！

気になる翻訳があったので、一文だけ変更しました [e30234a](https://github.com/railsgirls-jp/railsgirls.jp/pull/689/commits/e30234ac3bdbfb0f1a43ff62d26e1deeb1ee95f2)

ご確認をお願いいたします 🙏

2023-05-28 21:59 UTC, urimaro approved these changes
> 改行などを追加して原文と揃えました！

対応いただき、ありがとうございます！
確認しました

> 気になる翻訳があったので、一文だけ変更しました

以下の文の翻訳ですね

> We can the relationship between ideas and comments to fetch them from the database and show them in your app.

データベースから取得する対象がより明確になったと思います:+1:
原文に動詞がなかったことに今気づきました…

2023-05-29 13:40 UTC, yukyu30 commented
ご確認いただきありがとうございました！

> 原文に動詞がなかったことに今気づきました…

こちらはrailsgirls.comの原文の方へPR出しておきました！
https://github.com/railsgirls/guides.railsgirls.com/pull/524

2023-05-29 22:26 UTC, merged