linuxでのセットアップの部分を和訳
railsgirls-jp/railsgirls.jp pull request #690
Opened 2023-05-20 20:10 UTC by kyokucho1989

#686
_pages/install/linux.md
Linuxでの作業環境の構築について、和訳を行いました。

2023-05-25 05:26 UTC, urimaro requested changes
翻訳にご協力いただき、ありがとうございます！
いくつかコメントしましたので、ご確認ください:pray:

2023-05-25 05:26 UTC, urimaro commented on _pages/install/linux.md
> +Ruby on Railsの開発環境をインストールするためには、ただ、以下の行をコピーしてLinuxディストリビューション(Ubuntu または Fedora)に貼り付けてEnterを押すだけです。スクリーンに飛び交うテキストをお楽しみください。インストールにはかなり時間がかかります。作業を始める前に飲み物をとることをおすすめします。
> Linuxディストリビューション(Ubuntu または Fedora)に貼り付けて

「for your Linux distribution」は「the lines」にかかっているのではないかと思いました
このことを踏まえて以下のような訳はいかがでしょうか？

- あなたが使っているLinuxディストリビューション(Ubuntu または Fedora)向けの行をコピーし、貼り付けて

「your」を補足して「あなたが使っている」としました

2023-05-25 05:26 UTC, urimaro commented on _pages/install/linux.md
> +## _1._ 依存関係のインストール
見出しは他のページにならって「〜しよう」といった促す表現にしていただけないでしょうか:pray:
「Ubuntuの場合」「Fedoraの場合」は今のままで結構です

2023-05-25 05:26 UTC, urimaro commented on _pages/install/linux.md
> +Curlをインストールしてください。これは次のステップでスクリプトをインストールするのに必要です。
> スクリプトをインストールするのに

「run the install script」とあるので「インストールスクリプトを実行するのに」という訳はいかがでしょうか

2023-05-25 05:26 UTC, urimaro commented on _pages/install/linux.md
> +アプリケーション生成コマンド（以下のコマンド）を実行して、全てが動作していることを確認します。
> アプリケーション生成コマンド（以下のコマンド）を実行して、

「()」はつけずに、文頭に持ってきて良いと思います

- 以下のアプリケーション生成コマンドを実行して、

2023-05-25 05:26 UTC, urimaro commented on _pages/install/linux.md
> +カレントディレクトリをアプリケーションに移動し、
ディレクトリを移動すると思ってしまう人がいるかもしれないですので(Linux使っている時点で初学者ではないとは思いますが…)、以下のような訳はいかがでしょうか

- カレントディレクトリをアプリケーションのディレクトリに変更し

もっと単純にしても良いかもしれません

- アプリケーションのディレクトリに移動し、

2023-05-25 05:26 UTC, urimaro commented on _pages/install/linux.md
>  {% endcoach %}
せっかく翻訳していただいたのに大変申し訳ないのですが、この部分の翻訳は以下のファイルとそろえてください:pray:
＜ `Go to <http://localhost:3000>` から `{% endcoach %}` まで

https://github.com/railsgirls-jp/railsgirls.jp/blob/master/_pages/install/macos.md

本家を確認したところ、ほとんど同じ表現なので、本家で共通化したほうが良い部分だと考えています
お手数ですが、よろしくお願いします:pray:

2023-05-25 20:42 UTC, kyokucho1989 commented
@urimaro 
指摘ありがとうございます！修正しました！

2023-05-25 22:44 UTC, urimaro requested changes
対応ありがとうございます
1つだけコメントしました
確認をお願いします:pray:

2023-05-25 22:44 UTC, urimaro commented on _pages/install/linux.md
> +Ruby on Railsの開発環境をインストールするためには、ただ、以下の行をコピーしてあなたが使っているLinuxディストリビューション(Ubuntu または Fedora)向けの行をコピーし、貼り付けてEnterを押すだけです。スクリーンに飛び交うテキストをお楽しみください。インストールにはかなり時間がかかります。作業を始める前に飲み物をとることをおすすめします。
> 以下の行をコピーしてあなたが使っているLinuxディストリビューション(Ubuntu または Fedora)向けの行をコピーし、

コピーすることが重複してしまっているようです

2023-05-26 20:13 UTC, kyokucho1989 commented on _pages/install/linux.md
> +Ruby on Railsの開発環境をインストールするためには、ただ、以下の行をコピーしてあなたが使っているLinuxディストリビューション(Ubuntu または Fedora)向けの行をコピーし、貼り付けてEnterを押すだけです。スクリーンに飛び交うテキストをお楽しみください。インストールにはかなり時間がかかります。作業を始める前に飲み物をとることをおすすめします。
修正しました！

2023-05-27 01:53 UTC, urimaro approved these changes
対応ありがとうございました
LGTM:+1:です

2023-05-29 22:26 UTC, merged