「自分流の手引きを送る手順」ページに残っている英文を翻訳
railsgirls-jp/railsgirls.jp pull request #694
Opened 2023-05-21 04:47 UTC by sontixyou

Issue: https://github.com/railsgirls-jp/railsgirls.jp/issues/693

「自分流の手引きを送る手順」ページに残っている英文を翻訳しました。
該当ページは、[こちら](http://localhost:4000/contributing)です

2023-05-25 22:28 UTC, urimaro requested changes
翻訳にご協力いただき、ありがとうございます！
コメントしましたので、ご確認ください:pray:

2023-05-25 22:28 UTC, urimaro commented on _pages/contributing.md
> +4. このファイルでは、次の例になるように、ファイルの先頭にいくつかのYAML front matterを追加する必要があります。この例は、あなたが閲覧している本手引きから引用しています。
> front matter

一般的ではないかもしれませんが、序文や目次を意味する「前付け」という言葉に相当するようです
このことを踏まえて、以下のような訳はいかがでしょうか

* このファイルでは、次の例のように、ファイルの先頭にYAMLで前付けを追加する必要があります。

2023-05-26 02:49 UTC, sontixyou commented on _pages/contributing.md
> +4. このファイルでは、次の例になるように、ファイルの先頭にいくつかのYAML front matterを追加する必要があります。この例は、あなたが閲覧している本手引きから引用しています。
「前付け」という言葉は、初めて知りました！！

2023-05-27 01:54 UTC, urimaro approved these changes
対応ありがとうございました
LGTM:+1:です

2023-05-29 22:28 UTC, merged