「Test your app with RSpec」を翻訳
railsgirls-jp/railsgirls.jp pull request #699
Opened 2023-05-22 13:01 UTC by inoue-ryoki

「Test your app with RSpec」を翻訳しました。

fix: https://github.com/railsgirls-jp/railsgirls.jp/issues/672

2023-05-22 13:05 UTC, inoue-ryoki commented
ローカルのスクショです。
![screencapture-localhost-4000-testing-rspec-2023-05-22-21_53_13](https://github.com/railsgirls-jp/railsgirls.jp/assets/76472399/2a91f883-5a12-4b2f-86fe-390727887bd2)

2023-05-27 04:46 UTC, urimaro requested changes
翻訳にご協力いただき、ありがとうございます！
いくつかコメントしましたので、ご確認ください:pray:

2023-05-27 04:46 UTC, urimaro commented on _pages/testing-rspec.md
> +## *1.*RSpecのgemを追加する
タイトル同様、見出しも「〜しよう」のように促す表現でお願いします:pray:
(翻訳の指針のようなものは、まとめる予定です)

2023-05-27 04:46 UTC, urimaro commented on _pages/testing-rspec.md
> +Gemfileを開き、:development, :testのendタグの上に、以下の行を追加します。
`Gemfile` のように原文でコードとして表現されている場合、原文にならってください:pray:
また、読点は「、」で統一してください

2023-05-27 04:46 UTC, urimaro commented on _pages/testing-rspec.md
> +gemをインストールします。
ここは原文に従って分けてしまうと、かえって分かりにくくなると思いました
前の文「以下を実行します」に含めて訳してしまって良いと思います

2023-05-27 04:46 UTC, urimaro commented on _pages/testing-rspec.md
> +次に`spec/`ディレクトリを作成します。
「inside your application」が抜けてしまっているようです
意味は十分通じると思いますが、原文を尊重したいので、意図的に省略したのでなければ、含めて訳してみてください:pray:

2023-05-27 04:46 UTC, urimaro commented on _pages/testing-rspec.md
> +Rubyistはよく「テスト」と「仕様」という言葉を使い分けていますが、それはテストを「specs」フォルダに格納するためです。そのためには、以下の手順を実行します。
> …「テスト」と「仕様」とうい言葉を使い分けていますが、

「interchangeably」は「交換可能で、混同されて」という意味のようなので、以下のような訳はいかがでしょうか？

* 「テスト」と「仕様」という言葉を区別せずに使っていますが

---

原文との比較がしやすいように、改行位置は原文とあわせてください:pray:

2023-05-27 04:46 UTC, urimaro commented on _pages/testing-rspec.md
> +Railsで簡潔な方法でそれを行うために、ideaモデルのテストを作成します。
原文の「to do that」は「creating a test」を指しているんじゃないかと思いました
ですので、以下のような訳はいかがでしょうか？

* `idea` モデルのテストを作成しますが、Railsで簡潔に行うには

2023-05-27 04:46 UTC, urimaro commented on _pages/testing-rspec.md
> +* specフォルダの中にmodelsフォルダを作成するため以下をターミナルで実行します。
原文同様、コード( `` で囲む )として表現してください:pray:

2023-05-27 04:46 UTC, urimaro commented on _pages/testing-rspec.md
> +これは、テストがまだ実装されていないため保留中であることを出力します。
「出力されます」と受動態で表現したほうが読みやすいかもしれないと思いました
個人的な好みに近い話なので、採用するかどうかはお任せします

2023-05-27 04:46 UTC, urimaro commented on _pages/testing-rspec.md
> +その新しいファイル内で、最初のテストでideaに名前があることを確認します。そのため仕様の1つを説明しましょう。
> …ファイル内で、最初のテストで…

「最初のテストで」を文末に持っていくと読みやすいかもしれないと思いました
個人的な好みに近い話なので、採用するかどうかはお任せします

* その新しいファイルの中で、アイデアに名前があることを最初のテストで確認します  
    この場合の idea はモデルやクラス名ではなく、一般的な意味だと思ったので日本語(カタカナ)に訳しました

2023-05-27 04:46 UTC, urimaro commented on _pages/testing-rspec.md
> +それをどうにかしていきます。
「どうにかする」は良くないことを正すような印象があるように思いました
原文は「保留中なものをどうにかする」という意味でこの表現を使っているのかなと思いましたが、
この後でやっていることは「テストの実装」なので、
「ではテストを実装しましょう！」のように読者にとってわかりやすく意訳しても良さそうに思いました

2023-05-27 04:46 UTC, urimaro commented on _pages/testing-rspec.md
> +このテストを完成させますか?それとも他のテストについて考えますか？
全角と半角の「？」が混在しているように見えました
全角で統一してください:pray:

2023-05-27 04:46 UTC, urimaro commented on _pages/testing-rspec.md
> +## *4.*テストでTo Doにマークを付ける
テストに対してマークをつけると思うので、以下のような訳はいかがでしょうか

* テストにTo Doマークを付けてみよう

2023-05-27 04:46 UTC, urimaro commented on _pages/testing-rspec.md
> +## *5.*行動主導型開発
「Behaivor-Driven Development」は「振る舞い駆動開発」「ビヘイビア駆動開発」とう訳が割当たっていることが多いので、どちらかを採用したほうが良さそうです
ちなみにWikipediaでは「ビヘイビア駆動開発」でした

* [ビヘイビア駆動開発](https://ja.wikipedia.org/wiki/%E3%83%93%E3%83%98%E3%82%A4%E3%83%93%E3%82%A2%E9%A7%86%E5%8B%95%E9%96%8B%E7%99%BA)

「ビヘイビア駆動開発」を採用するのであれば、「ビヘイビア駆動開発をしてみよう」などはいかがでしょうか

2023-05-27 04:46 UTC, urimaro commented on _pages/testing-rspec.md
> +それではテストを楽しんでください。
完全に個人的な意見ですが…
プログラミング言語Rubyは「Happy」がキーワードになっている面もあると思うので「Happyテスティング！」でも良いかもしれません

2023-05-27 04:46 UTC, urimaro commented on index.html
> +    <p>自動で実行するテストを作成し、アプリケーションが期待通りに動作することを確認します。</p>
他のページにならい「app」の訳は「アプリ」でお願いします:pray:

2023-05-27 04:46 UTC, urimaro commented on _pages/testing-rspec.md
> +もう一人でいろんなテストを作れるようになったのではないでしょうか。もっといろんなテストを書きたい時はコーチに遠慮なく相談してください。
「to do that」が抜けてしまっているようです
意味は十分通じると思いますが、原文を尊重したいので、意図的に省略したのでなければ、含めて訳してみてください:pray:

2023-06-04 23:32 UTC, inoue-ryoki commented
@urimaro 
丁寧にレビューありがとうございます。
修正しましたので、ご確認よろしくお願いいたします。

2023-06-05 22:25 UTC, urimaro requested changes
対応いただき、ありがとうございます！
2点コメントしました
確認をお願いします:pray:

2023-06-05 22:25 UTC, urimaro commented on _pages/testing-rspec.md
> +ideaモデルのテストを作成しますが、Railsで簡潔に行うには
`idea` のように原文でコードとして表現されている場合、原文にならってください🙏
L63行目 `spec` もお願いします

2023-06-05 22:25 UTC, urimaro commented on _pages/testing-rspec.md
> +これは、テストがまだ実装されていないため保留中であることを出力されます。
> 保留中であることを

「保留中であることが」のほうが自然だと思いました
文全体の具体例をコメントすべきでした
すみません:bow:

2023-06-06 11:24 UTC, inoue-ryoki commented on _pages/testing-rspec.md
> +これは、テストがまだ実装されていないため保留中であることを出力されます。
@urimaro 
修正したので、ご確認よろしくお願いいたします。

2023-06-07 00:00 UTC, urimaro approved these changes
対応いただき、ありがとうございました
LGTM:+1:です！

2023-06-07 00:15 UTC, merged