Translate Web Fundamentals Tutorial
railsgirls-jp/railsgirls.jp pull request #712
Opened 2023-06-11 07:58 UTC by daiki0381

# Issue

#710 

# 概要

[Web Fundamentals Tutorial](https://railsgirls.jp/sinatra)を翻訳しました。

![Rails-Girls-Japanese](https://github.com/railsgirls-jp/railsgirls.jp/assets/98577773/a97a139e-60f8-443a-9d56-2dacd4d84afa)

2023-06-16 01:01 UTC, urimaro requested changes
翻訳にご協力いただき、ありがとうございます！
いくつかコメントしましたので、ご確認ください:pray:

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +今回は、[**Sinatra**](http://www.sinatrarb.com/)をツールとして使い、Webの基本的な原則をいくつか紹介します。Sinatraは、Rubyで最小限の労力でWebアプリケーションを作成するための小さなフレームワークです。[Sinatraで作られたものはこちら](http://www.sinatrarb.com/wild.html)にリストアップされています。
> Rubyで最小限の労力で

「Rubyを使って最小限の労力で」のように「で」が連続しないようにすると自然かもしれません
個人的な意見なので、スルーしていただいても構いません

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +ブラウザでリクエストを行うには、URLを使用する必要があります。URLには、サーバーが正しいレスポンスを送れるように、どのような情報をリクエストしているのか、多くの情報が含まれています。
> ブラウザでリクエストを行うには、

「ブラウザでリクエストするには」「ブラウザでリクエストを送るには」といった表現のほうが自然かなと思いました
前者は「リクエスト」を動詞として扱い、後者は名詞として扱うイメージですね

他の訳文と表現をそろえるようにすると、読みやすくなりそうだなと思いました
リクエストとレスポンスは対になっているので、レスポンスの表現とそろえると、わかりやすくなりそうです

---

十分に意味が伝わる表現ですし、個人的な意見なので、スルーしていただいても構いません

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +* オプションとして、リクエストに関する追加情報を含むキーと値のペアとして、URLの末尾にパラメータがある場合があります。
> リクエストに関する追加情報を含むキーと値のペアとして、URLの末尾にパラメータがある場合があります。

「キーと値のペアとして」の位置を変えると読みやすくなるかもしれません

* リクエストに関する追加情報を含むパラメータが、キーと値のペアとして、URLの末尾にある場合があります。

個人的な意見なので、スルーしていただいても構いません

2023-06-16 01:01 UTC, urimaro commented on index.html
> +    <p>何が起こっているのか、より深く理解しましょう。</p>
原文を尊重したいので、意図的に省略したのでなければ `under the hood` も訳してみてください:pray:

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +Sinatraに`post`コードを追加してみましょう（getは外さないでね！）：
原文同様、「追加」を `*` で囲んでください:pray:

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +* 次に、コーヒーのパラメータを保存する行を`get`コードから移動します。 (これは`template`への呼び出しの上にあることを確認してください)
原文同様、「移動」を `*` で囲んでください:pray:

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +以下の演習では、リソースフォルダ名とHTTP動詞の組み合わせを使用して、どのようにブラウザがアプリケーションと通信するのかを示す、簡単なコーヒーリストアプリケーションを作成します。
> どのようにブラウザがアプリケーションと通信するのかを示す

アプリケーションの機能を説明だと思ってしまうかもしれないと思いました
前方に移動させるのはいかがでしょうか？

> 以下の演習では、どのようにブラウザがアプリケーションと通信するのかを示すために、リソースフォルダ名とHTTP動詞の組み合わせを使った簡単なコーヒーリストアプリケーションを作成します。

---

他のガイドにならって、`application` は「アプリ」と訳してください:pray:

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +`app.rb`というファイルを作成し、以下をSublime Textに貼り付ける：
他の文にならって、文末の表現をそろえてください:pray:

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +現在のサイトを見る： [http://localhost:4567](http://localhost:4567)
他の文にならって、文末の表現をそろえてください:pray:

- 現在のサイトを確認します： [http://localhost:4567](http://localhost:4567)

---

言葉を補ったり、順番を入れ替えるとわかりやすくなるかもしれません
個人的な意見なので、スルーしていただいても構いません

- 次のURLにアクセスして、現在のサイトを確認します： [http://localhost:4567](http://localhost:4567)
- [http://localhost:4567](http://localhost:4567) にアクセスして、現在のサイトを確認します

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +"/"と書いてあるところは、ルートURLを指定していますが、好きなパス名にすることができます。
> "/"と書いてあるところは、

`app.rb` に書いたのは読者のはずなので、「"/"と書いたところは」のほうが良いかもしれません
個人的な意見なので、スルーしていただいても構いません

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +同じファイルに、上のブロックと同じ構文を使用して、別のページに訪問するコードを追加してみてください。
> 別のページに訪問するコードを

「creating more pages」とあるので、以下のような表現はいかがでしょうか？

- さらに訪問するページを
- アクセスできるページをもっと

---

以下の文が抜けてしまっているようです

> You can add as many pages as you like, and have them say whatever you want.

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +**Coach:** パラメータ名がどこから来ているのか、クエスチョンマークは何をしているのかについて話します。
「〜しましょう」「〜しよう」のように促す表現に変えてください:pray:
166行目もお願いします

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +**Note:** "backup from WEBrick"と表示されている場合、更新するたびに複数のGETリクエストが表示されることがあります。実際に発行されているのは1つのリクエストだけなので、他のリクエストは無視しても大丈夫です。
以下の部分が抜けてしまっているようです

> Ruby's build-in webserver

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +## *5.* グローバル変数
原文との差分をわかりやすくするため、空行の数をそろえてください:pray:

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +分かりやすくするために、コーヒーの詳細を変数に格納することにします。リクエスト間で利用できるように、[**グローバル変数**](http://en.wikipedia.org/wiki/Global_variable)を使用する必要があります。これは、Railsがモデル層と呼んでいるものを大幅に簡略化したものです。
> モデル層と呼んでいるもの

「Rails calls」とあるので「Railsがモデルを呼び出しているもの」かなと思いました
「もの」をイメージしやすくすると以下のような感じでしょうか

> これは、Railsがモデル層を呼び出す処理を…

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +ここで、リクエストを受け取ったときに、その情報を `$coffees` で定義した配列に格納する必要があります。フォームに必要事項を入力して送信ボタンをクリックすると、サーバーに送信される情報がURLの末尾の?の後に置かれることを忘れないでください。
意図的かもしれませんが、以下が抜けてしまっているようです

> to be sent back to the server

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +グローバル変数は配列なので、行き詰まった場合は、[Rubyのドキュメント](http://www.ruby-doc.org/core-2.1.0/Array.html#method-i-3C-3C)を参照してください。
Arrayが抜けてしまっているようです

> try [Ruby's Array documentation]

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +パラメータが正しく格納されていれば、ブラウザを更新して、毎回新しいハッシュが `$coffees` の配列に追加されることを確認できるはずです。
> `$coffees` の配列に追加される…

「`$coffees` が格納されている配列に追加される…」と読めてしまうかもしれないと思いました
「配列 `$coffees` に追加される」とするか、「の配列」を削除すると良いかもしません

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +コーヒーの保存のところで見たように、ブラウザを更新すると、アプリは繰り返し`$coffees`に情報を追加します。これは、`get`コードがリクエストされるたびに、URLからパラメータを保存しているためです。
global variableが抜けてしまっているようです

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +これは、`GET`リクエストはアプリに情報を追加するようなことをしてはいけないということを言及する良いポイントです。この例のようにうまくいくこともありますが、意図しない副作用が発生することがあります。この場合は `POST` リクエストを使用するのがよいでしょう。
> 意図しない副作用が発生することがあります。

「it's too easy」なので以下のように言い切ってしまって良さそうに思いました

- 意図しない副作用が簡単に発生してしまいます

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +これは、リクエストされたルートが存在しないことを伝えています。HTTPエラー番号404としても知られているかもしれません： *page not found*と同じです。
意図的かもしれませんが、「Sinatra's way」が抜けてしまっているようです

---

> HTTPエラー番号404としても知られているかもしれません： *page not found*と同じです。

「page not found」は404の説明だと思ったので、404とまとめても良いかもしれないと思いました

- HTTPエラー番号404 *page not found* として、ご存知の方もいるかもしれません

個人的な意見なのでスルーしていただいても構いません

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +* ブラウザをリフレッシュして、新しいコーヒーを投稿してください。
> ブラウザをリフレッシュして

「refresh」は「更新」としたほうが、ページ全体の統一感が出て読みやすくなりそうに思いました

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +**Uh oh!** Sinatraのエラーページを見たことのない方は、Sinatraの素敵なエラーページへようこそ。一番下のメッセージにはこう書いてあるはずです：
> 一番下のメッセージには

今の表現だと「いくつかあるメッセージの中の一番下のメッセージ」と読めてしまうかもしれないと思いました
試していなので、はっきりとしたことは言えませんが、「at the bottom」は「画面の下部」のことかなと思いました
メッセージの一部を意味している場合でも、複数行のメッセージが紹介されていることから、「一番下」より「下のほう」としたほうが自然かなと思いました

試さずにコメントしているので、スルーしていただいても構いません

2023-06-16 01:01 UTC, urimaro commented on _pages/sinatra.md
> +続けてみたいという方は、ぜひお試しください：
意図的かもしれませんが「you were fast」が抜けてしまっているようです

2023-07-24 08:58 UTC, daiki0381 commented
@urimaro ご丁寧にレビューありがとうございます🙇‍♂️ ご連絡が遅くなり大変申し訳ございません。少々立て込んでおりまして、7月末までにレビュー対応行いたいと思います！

2023-08-01 07:10 UTC, daiki0381 commented on _pages/sinatra.md
> +今回は、[**Sinatra**](http://www.sinatrarb.com/)をツールとして使い、Webの基本的な原則をいくつか紹介します。Sinatraは、Rubyで最小限の労力でWebアプリケーションを作成するための小さなフレームワークです。[Sinatraで作られたものはこちら](http://www.sinatrarb.com/wild.html)にリストアップされています。
こちら[501ad8f](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/501ad8ff26070a4b83990f57055d479b5c2f5026)で修正しました。

2023-08-01 07:10 UTC, daiki0381 commented on _pages/sinatra.md
> +ブラウザでリクエストを行うには、URLを使用する必要があります。URLには、サーバーが正しいレスポンスを送れるように、どのような情報をリクエストしているのか、多くの情報が含まれています。
こちら[adc7b54](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/adc7b546ddb20714830f174f16890906b1aeb851)で修正しました。

2023-08-01 07:11 UTC, daiki0381 commented on _pages/sinatra.md
> +* オプションとして、リクエストに関する追加情報を含むキーと値のペアとして、URLの末尾にパラメータがある場合があります。
こちら[808e227](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/808e227a4374698bc10699cc62948930cc86e3fc)で修正しました。

2023-08-01 07:11 UTC, daiki0381 commented on index.html
> +    <p>何が起こっているのか、より深く理解しましょう。</p>
こちら[8899f8f](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/8899f8fcb6b1fdb75cff966b8c24fc450a709ab4)で修正しました。

2023-08-01 07:12 UTC, daiki0381 commented on _pages/sinatra.md
> +Sinatraに`post`コードを追加してみましょう（getは外さないでね！）：
こちら[398a9f7](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/398a9f7f8fd02c286cf7ac3f184bb8a8e312ecf2)で修正しました。

2023-08-01 07:13 UTC, daiki0381 commented on _pages/sinatra.md
> +* 次に、コーヒーのパラメータを保存する行を`get`コードから移動します。 (これは`template`への呼び出しの上にあることを確認してください)
こちら[a4925e9](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/a4925e90083be20f2203a24a42b130e42e91081e)で修正しました。また併せて「上」も同様に修正しました！

2023-08-01 07:15 UTC, daiki0381 commented on _pages/sinatra.md
> +以下の演習では、リソースフォルダ名とHTTP動詞の組み合わせを使用して、どのようにブラウザがアプリケーションと通信するのかを示す、簡単なコーヒーリストアプリケーションを作成します。
こちら[4d3c3e4](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/4d3c3e4246b75233895df2fb6b7a3fce42bd3d08)で修正しました。

2023-08-01 07:15 UTC, daiki0381 commented on _pages/sinatra.md
> +`app.rb`というファイルを作成し、以下をSublime Textに貼り付ける：
こちら[4d3c3e4](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/4d3c3e4246b75233895df2fb6b7a3fce42bd3d08)で修正しました。

2023-08-01 07:15 UTC, daiki0381 commented on _pages/sinatra.md
> +現在のサイトを見る： [http://localhost:4567](http://localhost:4567)
こちら[4d3c3e4](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/4d3c3e4246b75233895df2fb6b7a3fce42bd3d08)で修正しました。

2023-08-01 07:16 UTC, daiki0381 commented on _pages/sinatra.md
> +"/"と書いてあるところは、ルートURLを指定していますが、好きなパス名にすることができます。
こちら[f5bd237](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/f5bd2376624e1eb65042028abe22cd2e6f32492b)で修正しました。

2023-08-01 07:17 UTC, daiki0381 commented on _pages/sinatra.md
> +同じファイルに、上のブロックと同じ構文を使用して、別のページに訪問するコードを追加してみてください。
こちら[d41c2d5](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/d41c2d5ac666fb109876fcaf7eb7f33590791976)で修正しました。

2023-08-01 07:17 UTC, daiki0381 commented on _pages/sinatra.md
> +**Coach:** パラメータ名がどこから来ているのか、クエスチョンマークは何をしているのかについて話します。
こちら[415fd5a](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/415fd5a3c9c70ac817a17f6d1735dfc4a8216451)で修正しました。

2023-08-01 07:17 UTC, daiki0381 commented on _pages/sinatra.md
> +**Note:** "backup from WEBrick"と表示されている場合、更新するたびに複数のGETリクエストが表示されることがあります。実際に発行されているのは1つのリクエストだけなので、他のリクエストは無視しても大丈夫です。
こちら[3523c52](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/3523c523bca4048888a960e9a4cf082431ed287b)で修正しました。

2023-08-01 07:18 UTC, daiki0381 commented on _pages/sinatra.md
> +## *5.* グローバル変数
こちら[13087b3](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/13087b3c3bbd9eb4d70a0719724d79d1b5a1b5e6)で修正しました。

2023-08-01 07:18 UTC, daiki0381 commented on _pages/sinatra.md
> +分かりやすくするために、コーヒーの詳細を変数に格納することにします。リクエスト間で利用できるように、[**グローバル変数**](http://en.wikipedia.org/wiki/Global_variable)を使用する必要があります。これは、Railsがモデル層と呼んでいるものを大幅に簡略化したものです。
こちら[ee25af8](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/ee25af8a7e6b6bbb420d2f1eefc103a091101fab)で修正しました。

2023-08-01 07:18 UTC, daiki0381 commented on _pages/sinatra.md
> +ここで、リクエストを受け取ったときに、その情報を `$coffees` で定義した配列に格納する必要があります。フォームに必要事項を入力して送信ボタンをクリックすると、サーバーに送信される情報がURLの末尾の?の後に置かれることを忘れないでください。
こちら[b3b3ac1](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/b3b3ac11b7f491320dff932be0bd0c93b0c346d1)で修正しました。

2023-08-01 07:18 UTC, daiki0381 commented on _pages/sinatra.md
> +グローバル変数は配列なので、行き詰まった場合は、[Rubyのドキュメント](http://www.ruby-doc.org/core-2.1.0/Array.html#method-i-3C-3C)を参照してください。
こちら[0f454fb](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/0f454fb32d2d2391a823af22a75d6159dd9b471f)で修正しました。

2023-08-01 07:19 UTC, daiki0381 commented on _pages/sinatra.md
> +パラメータが正しく格納されていれば、ブラウザを更新して、毎回新しいハッシュが `$coffees` の配列に追加されることを確認できるはずです。
こちら[0552bc5](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/0552bc5ea72a0da32a993c9b1b06955ab62f1567)で修正しました。

2023-08-01 07:19 UTC, daiki0381 commented on _pages/sinatra.md
> +コーヒーの保存のところで見たように、ブラウザを更新すると、アプリは繰り返し`$coffees`に情報を追加します。これは、`get`コードがリクエストされるたびに、URLからパラメータを保存しているためです。
こちら[5b416c2](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/5b416c284021b10653e025b60eeaca2f27783130)で修正しました。

2023-08-01 07:19 UTC, daiki0381 commented on _pages/sinatra.md
> +これは、`GET`リクエストはアプリに情報を追加するようなことをしてはいけないということを言及する良いポイントです。この例のようにうまくいくこともありますが、意図しない副作用が発生することがあります。この場合は `POST` リクエストを使用するのがよいでしょう。
こちら[67ba07a](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/67ba07a09b34cc6ed422c54208395eacbb507b49)で修正しました。

2023-08-01 07:20 UTC, daiki0381 commented on _pages/sinatra.md
> +これは、リクエストされたルートが存在しないことを伝えています。HTTPエラー番号404としても知られているかもしれません： *page not found*と同じです。
こちら[1f3dd8c](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/1f3dd8ce3da7ad37213246477edf0e36443e3159)で修正しました。

2023-08-01 07:20 UTC, daiki0381 commented on _pages/sinatra.md
> +* ブラウザをリフレッシュして、新しいコーヒーを投稿してください。
こちら[5e1ac29](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/5e1ac29d367bcfb693d435475c2b75fa2f426800)で修正しました。

2023-08-01 07:23 UTC, daiki0381 commented on _pages/sinatra.md
> +**Uh oh!** Sinatraのエラーページを見たことのない方は、Sinatraの素敵なエラーページへようこそ。一番下のメッセージにはこう書いてあるはずです：
> メッセージの一部を意味している場合でも、複数行のメッセージが紹介されていることから、「一番下」より「下のほう」としたほうが自然かなと思いました

ご提案していただいた方が自然なので[52a6f8b](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/52a6f8ba4fb38e54fc665156b58d697e00f87431)で修正しました。参考にSinatraのエラーページは下記のようになっていました。

▼Sinatraのエラーページ

<img width="789" alt="スクリーンショット 2023-08-01 16 01 52" src="https://github.com/railsgirls-jp/railsgirls.jp/assets/98577773/473cb7bd-d633-4caa-a882-a56ed3227319">

2023-08-01 07:24 UTC, daiki0381 commented on _pages/sinatra.md
> +続けてみたいという方は、ぜひお試しください：
こちら[5f97dc2](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/5f97dc2eaddb85f085fbfc0c67365c419cfe7827)で修正しました。

2023-08-01 07:25 UTC, daiki0381 commented
@urimaro 遅くなってしまい大変申し訳ございません。再度レビューお願いします🙇‍♂️

2023-08-01 07:33 UTC, daiki0381 commented
また併せて、Translate Web Fundamentals Tutorialページの「6.」が2回登場していて、番号がおかしくなっていたので修正しました。guides.railsgirls.comの方にもPRを投げておきました。

https://github.com/railsgirls/guides.railsgirls.com/pull/536

2023-09-02 07:10 UTC, urimaro requested changes
お待たせしてしまって、すみません:bow:
細かいところまで対応していただき、ありがとうございます
1点、フィードバックしましたので、ご確認ください:pray:

2023-09-02 07:10 UTC, urimaro commented on _pages/sinatra.md
> +**Note:** もしSinatraがRubyの組み込みWebサーバである"WEBrickからのバックアップ"のログが表示されている場合、更新するたびに複数のGETリクエストが表示されるかもしれません。実際に発行されているのは1つのリクエストだけなので、他のリクエストは無視しても大丈夫です。
> もしSinatraがRubyの組み込みWebサーバである"WEBrickからのバックアップ"のログが表示されている場合、

ユーザーには `backup from WEBrick` と表示されると思うので、そのままのメッセージのほうが、わかりやすいんじゃないかと思いました
いかがでしょうか

「Ruby's built-in webserver,」はメッセージ内の「WEBrick」を説明しているので、文を組み立てるのが難しいですね
`()` で囲んでも良いかもしれません

* Sinatraのログに "backup from WEBrick"(WEBrickはRubyに組み込まれているWebサーバーです)と表示されている場合、

2023-09-02 12:10 UTC, daiki0381 commented on _pages/sinatra.md
> +**Note:** もしSinatraがRubyの組み込みWebサーバである"WEBrickからのバックアップ"のログが表示されている場合、更新するたびに複数のGETリクエストが表示されるかもしれません。実際に発行されているのは1つのリクエストだけなので、他のリクエストは無視しても大丈夫です。
ご提案いただいた文章の方が分かりやすいですね！こちら[4e74b64](https://github.com/railsgirls-jp/railsgirls.jp/pull/712/commits/4e74b64a112c80a5a1edb5e9577e22776f297e97)で修正しました！

2023-09-02 12:10 UTC, daiki0381 commented
@urimaro レビュー対応しました！再度レビューお願いします🙇‍♂️

2023-09-03 12:08 UTC, urimaro approved these changes
ひとつひとつ丁寧に対応していただき、ありがとうございました
LGTM:+1:です！

2023-09-03 12:25 UTC, merged