ruby-atmの翻訳
railsgirls-jp/railsgirls.jp pull request #724
Opened 2023-06-24 05:50 UTC by kyokucho1989

#713 

atmの箇所を翻訳しました。

2023-06-26 00:19 UTC, urimaro commented
@kyokucho1989 
別件ですが、PRとissueを紐付けておくと、PRがmergeされるとissueが自動でcloseされます(※)
参考まで

ref. [Pull RequestをIssueにリンクする](https://docs.github.com/ja/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

※ ただし、merge先がdefaultブランチの場合

2023-07-04 00:46 UTC, urimaro requested changes
翻訳にご協力いただき、ありがとうございます！
日本語にするのがむずかしい表現が結構あったと思います
いくつかコメントしていますので、確認してください:pray:

表現や文の組み立てをそろえると読みやすくなると思いました

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +*翻訳者: kyokucho1989, [@kyokucho1989](https://twitter.com/kyokucho_1989)*
以下のガイドにならって、`Created by` と同じ行に書いてください:pray:
https://railsgirls.jp/github

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +この演習では、ATMから預金を引き出す関数を作成します。やっていきましょう！　たくさん質問をしたり、Googleで検索したり、コンピュータから一歩離れる準備をしておきましょう。難しいですが、得るものは多いです！
言いたいことはわかるけれど、日本語にするのがむずかしい部分ですね

> やっていきましょう

文字通り読者に挑むような表現にしてみても良さそうに思いました
個人的な意見なので、スルーしても構いません

> …準備をしておきましょう。

この「準備をする」は「旅行の準備する」のような「必要なものをそろえる」という意味とは違う意味でお使いになったのかなと思いました
前の文が読者に挑戦するような表現なので「覚悟する」「心の準備をする」といった表現にしてはどうでしょう

> …多いです!

未来形なので「多いはずです」「多いと思います」という表現はいかがでしょうか

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +他のプログラマと意見を交換できるよう、ペア、グループもしくはリモートでのプログラミングをすべきです。テスト駆動開発を用いることになるでしょう。しかし、すべてのテストはあらかじめ書かれています。そのため、コードを書くことに集中できます。
> 意見を交換できるよう

うまい訳だなぁと思いました😊
参考になります

> プログラミングをすべきです。

他の文と比べてきつい表現かもしれないと思いました
「したほうが良い」といった表現はいかがでしょうか
個人的な意見なので、スルーしても構いません

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +**1. 新しいテストを実行する:**  前回のテストを削除し, 現在の手順のテストを貼り付けてください。*(それぞれの手順のためのテストは、その手順の下方に記載してます。)* テストを実行し、どのテストが失敗するか確認してください。 テキストエディタの SublimeTextでは、 <kbd>Ctrl</kbd>+<kbd>B</kbd> でテストを実行できます。 または、ターミナルを開き `
> 削除し，

読点は「、」で統一してください:pray:

> それぞれの手順のためのテストは

「それぞれの手順のテストは」のほうが自然かなと思いました

> 下方に記載しています

「下方に」は他の文と比べて硬い表現かもしれないと思いました
「終わりに」「最後に」という表現はいかがでしょうか

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +**2. テストを通過する:** 現在のステップの機能的な要件を満たすようにコードを編集します。全てのテストがパスしたとき、あなたの書いたコードが正しいことがわかります。
> テストを通過する

`make` が使われていることから「テストをパスさせる」「テストを通す」のほうが自然かなと思いました
他の訳文を見てみると「パス」という言葉を使っているようですので、「パスさせる」が良いかもしれません

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +**3. リファクタリング:** コードがきれいで理解しやすいものかどうか、確認してください。一部のステップには議論すべきポイントがあります。それについて、相手と話し合ってください。理解が進みますよ。
> リファクタリング

他の項目同様「〜する」といった表現のほうが、統一感があるように思いました
個人的な意見なのでスルーしても構いません

> コードがきれいで理解しやすいものかどうか、確認してください

読者に確認してほしいのは「すでに書いてあるコードがきれいで理解しやすいか」ではなく、「よりきれいで理解しやすくできる部分がないか」だと思いました
以下のような訳はいかがでしょうか

* できるだけきれいで理解しやすいコードになるように編集できる部分がないか確認してください
* コードができるだけきれいでわかりやすくなるように編集できる部分がないか確認してください

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +これらのステップはテスト駆動開発における**赤、緑、リファクタリング** のワークフローとして確認できるかもしれません。
> 赤、緑、リファクタリング

テスト駆動開発のリズムとして浸透していると思うので「レッド、グリーン、リファクタリング」のままで良いと思います

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +5ドル紙幣しか入っていないATMを考えてください。現金として引き出すことができれば `true` を、 そうでないなら `false` を返す関数を作ります。
他のガイドにならって、命令形は促すような表現にしてください:pray:
例えば「関数を作りましょう」というのはいかがでしょうか

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +標準モジュールの演算子 `%` は余りを出力します。 例えば `9 % 4` は `1` になります。(9を4で割った時の余りは1のため)。
> 標準モジュールの演算子

`modulus` なので「剰余演算子」「モジュロ演算子」が良いと思います

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +それでは、ここから関数を修正します。引数が引き出すことができる金額でなら、単純に `true` を返すのではなく、紙幣の枚数を返すようにします。
> 引数が引き出すことができる金額でなら、

以下のような表現のほうが自然かなと思いました

- 引数が引き出せる金額なら
- 引き出せる金額であれば

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +Rubyでは、ふたつの整数で割り算を行う場合、結果は最も近い整数に切り捨てられます。
この場合においては `whole numbers` は「正の整数」と訳したほうが良いかもしれません
一般的に「整数」は負の値も含まれますが、Rubyでは負の整数を正の整数で割った場合、以下のような結果になるためです

```
>> -25 / 10
=> -3
```

`whole number` は「0」を含む場合もあるようですが、今回の場合、0を割る/0で割ることは想定していないと思うので「正の整数」で良いと思いました

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +`/` 演算子は除算を示します。例えば、自分の年齢の半分に割り、それを変数に保存させたい場合、このように書きます。
> 除算を示します

「割り算を行います」「割り算をします」のほうが自然かなと思いました
個人的な意見なのでスルーしても構いません

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +紙幣の枚数を返すよりも、紙幣そのものの配列を返すようにコードを修正します。（この場合では、全て5ドル紙幣です）
> 返すよりも

「返すのではなく」のほうが自然かなと思いました

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +`[]` は空の配列と定義されています。`[1, 2]` は二つの要素（1と2）をもつ配列として定義されています。
> 空の配列と定義されています

「Rubyのルールとして定義されている」と言えるとは思いますが、この場面では「空の配列を定義します」のほうが自然かなと思いました
個人的な意見なのでスルーしても構いません

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +シフト演算子 (`<<`) を使えば、配列に要素を加えることができます。例えば、 `[10, 20] << 30` は30を配列に追加させ、結果として `[10, 20, 30]` という配列が得られます。
> シフト演算子

確かにレシーバーがIntegerなどの場合、`<<` はシフト演算子を意味すると思いますが、配列なので「シフト演算子」と呼ばないほうが良さそうに思いました
原文を尊重する意味でも「シャベル演算子」としていただけないでしょうか
(シャベル演算子はボッチ演算子、UFO演算子のような演算子の「あだ名」だと理解しています)

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +* `withdraw(11)` ならば、 `false` を返します。 11ドルは5ドル紙幣だけで作れないためです。
統一感を持たせるために「返します。」の後の空白は削除してください:pray:
他のテストケースも同様です

---

> …5ドル紙幣だけで作れないためです。

細かい話ですが「だけでは」のほうが自然かなと思いました
他の例も同様です

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +プログラミングでは、['マジックナンバー'](http://en.wikipedia.org/wiki/Magic_number_(programming)) は、悪いものとされています。（名前に騙されないで！） マジックナンバーとはコードに直接打ち込まれ（ハードコーディング）、なにもないところから *現れる* ような値です。値に対する明確な説明もありません。
> 悪いものとされています。（名前に騙されないで！）

細かい話ですが、閉じカッコの後に句点を置くのが一般的かなと思いました
他の文も同様です

---

> 値に対する明確な説明もありません

以下の比喩を説明していると思うので、前の文に含めたほうがわかりやすいんじゃないかと思いました

* なにもないところから現れるような値です

文が別れていると以下のように読めてしまうかもしれないと思いました

* 「なにもないところから現れるような値」かつ「値に対する明確な説明もない」

このように読んでしまった場合「なにもないところから現れるような値」がどのような値なのかわからなくなる可能性があると思います

例えば以下のような訳はいかがでしょうか

* マジックナンバーは、何を表しているのか明確な説明がないため、まるで何もないところから現れたような、プログラムに直接入力された(ハードコーディングされた)値のことです
* マジックナンバーは、プログラムに直接入力された(ハードコーディングされた)値、かつ何を表しているのか明確な説明がなく、まるで何もないところから現れたような値のことです

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +マジックナンバーは、同じようにハードコーディングされた値が複数箇所に現れている場合、特に問題になります。
> 同じように

値が同じマジックナンバーが複数使われていると、意味も含めて本当に同じなのか、値だけが同じなのか区別がつけにくくなるので、問題になると理解しています
ですので「同じ」のほうが良さそうに思いました

例えば以下のような感じでしょうか

* 複数の箇所で同じ値がハードコーディングされていると、マジックナンバーは特に問題になります

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +* `withdraw(18)` ならば、 `false` を返します。（18ドルは5ドル紙幣だけではつくれないため）
他の例では `,` 以降を別の文にしていると思います
`()` で囲むのか、別の文にするのか、統一してください:pray:

また「つくる」「作る」も統一したほうが読みやすいと思います:pray:

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +* `withdraw(11)` ならば、 `false` を返します。 11ドルは5ドル紙幣だけで作れないためです。
> 11ドルは5ドル紙幣だけで作れないためです。

「and $10」が抜けてしまっているようです

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +## *6.* 5ドル紙幣・10ドル紙幣、そして20ドル紙幣
中点「・」を使うのか、読点を「、」を使うのか統一してください:pray:

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +* `withdraw(11)` ならば、 `false` を返します。 11ドルは5ドル紙幣だけで作れないためです。
「and $10」が抜けてしまっているようです

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +**注意:** この点では、高額な紙幣の金額は低額な紙幣の金額を割り切ることができます。（例：20ドル/10ドル = 2）そうでない場合（50ドルと20ドル）はより事態が複雑になってしまいます。 このステップでは、簡単にするために、そのケースを意図的に扱いません。
> この点では

「この時点では」のほうが自然かなと思いました

> このステップでは、簡単にするために、そのケースを…

以下のように順番を入れ替えたほうが読みやすそうに思いました

* 簡単にするために、このステップではそのケースを…

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +配列が空であるかどうかを判定する：`my_array.empty?`
> 配列が空であるかどうかを

「配列が空であることを」言い切ったほうがわかりやすそうに思いました

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +配列が空ではないかを判定する：`!my_array.empty?`
上の文と同様です
特にこちらの文は、言い切ったほうがわかりやすくなるように思いました

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +* 特定の解決策が「機能する」とすると、そのコードの良し悪しを決定するのはなんでしょうか？
> …「機能する」と

`**` で囲むことはmarkdownとして意味があるので、「」で囲むのではなく `**` で囲んでください:pray:

2023-07-04 00:46 UTC, urimaro commented on _pages/ruby-atm.md
> +これまで、私たちはATMで扱える紙幣のうち、低額の種類の紙幣がそれより高額の紙幣の倍数となることを意識的に避けてきました。例えば、50ドルと20ドル紙幣のみ扱う、のように。(50は20で割り切ることはできない)　なぜこのケースが困難かわかりますか？ もしあなたの現在のコードが50ドル紙幣と20ドル紙幣しか利用可能でない場合、60ドルまたは110ドルをを引き出す場合はなにが起こりますか？ 自分の頭
> …倍数となることを…

「倍数にならないこと」かなと思いました

> …60ドルまたは110ドルをを引き出す場合は…

「を」が重複していました

2023-07-08 23:03 UTC, kyokucho1989 commented
@urimaro 
再度、翻訳部分修正しました！
確認をお願いします！

2023-07-09 23:48 UTC, urimaro requested changes
細かい部分まで対応していただき、ありがとうございます！

これまた細かい話で恐縮なのですが、体裁についてコメントしました
ご確認ください:pray:

2023-07-09 23:48 UTC, urimaro commented on _pages/ruby-atm.md
原文と比較しやすくするため、空行の数をそろえてください:pray:

2023-07-09 23:48 UTC, urimaro commented on _pages/ruby-atm.md
原文と比較しやすくするため、空行の数をそろえてください:pray:

2023-07-09 23:48 UTC, urimaro commented on _pages/ruby-atm.md
> +**1. 新しいテストを実行する:**  前回のテストを削除し、現在の手順のテストを貼り付けてください。*(それぞれの手順のテストは、その手順の終わりに記載してます。)* テストを実行し、どのテストが失敗するか確認してください。 テキストエディタの SublimeTextでは、 <kbd>Ctrl</kbd>+<kbd>B</kbd> でテストを実行できます。 または、ターミナルを開き `cd`
「。」の後の空白は意図的でしょうか
意図的でないならば、削除してください:pray:
他にもいくつかあるようです

2023-07-13 20:23 UTC, kyokucho1989 commented
@urimaro 
修正しました！よろしくお願いします

2023-07-15 03:56 UTC, urimaro commented on _pages/ruby-atm.md
> +**1. 新しいテストを実行する:**  前回のテストを削除し、現在の手順のテストを貼り付けてください。*(それぞれの手順のテストは、その手順の終わりに記載してます。)* テストを実行し、どのテストが失敗するか確認してください。 テキストエディタの SublimeTextでは、 <kbd>Ctrl</kbd>+<kbd>B</kbd> でテストを実行できます。 または、ターミナルを開き `cd`
@kyokucho1989 
L23、L44、L271を確認してください:pray:

2023-07-15 20:55 UTC, kyokucho1989 commented on _pages/ruby-atm.md
> +**1. 新しいテストを実行する:**  前回のテストを削除し、現在の手順のテストを貼り付けてください。*(それぞれの手順のテストは、その手順の終わりに記載してます。)* テストを実行し、どのテストが失敗するか確認してください。 テキストエディタの SublimeTextでは、 <kbd>Ctrl</kbd>+<kbd>B</kbd> でテストを実行できます。 または、ターミナルを開き `cd`
@urimaro 見落としてました…！　修正しました。

2023-07-16 00:00 UTC, urimaro approved these changes
細かいところまで対応いただき、ありがとうございました！
LGTM:+1:です

2023-07-16 00:00 UTC, merged