Touristic autism friendly spots
railsgirls-jp/railsgirls.jp pull request #727
Opened 2023-07-02 15:40 UTC by nyancat3

@urimaro
Issue https://github.com/railsgirls-jp/railsgirls.jp/issues/726 の対応です。
https://railsgirls.jp/touristic-autism_intro を翻訳しました。レビューよろしくお願いいたします！

元のコードが古く、https://github.com/railsgirls/guides.railsgirls.com/pull/305 のシンタックスハイライトや、http -> https 対応がされていなかったため、最初のcommit 3e56fb55be04925d5b250333b8388cecd7518fac でまず[英語版の最新状態](https://github.com/railsgirls/guides.railsgirls.com/blob/46464dc95921328c9d0ac228f73dc3623a9895b8/_pages/touristic-autism_intro.md?plain=1)に追従しています。

2023-07-05 23:46 UTC, urimaro commented
> 最初のcommit `3e56fb5` でまず英語版の最新状態に追従しています

ありがとうございます！

2023-07-08 02:44 UTC, urimaro requested changes
翻訳にご協力いただき、ありがとうございます！
いくつかコメントしていますので確認してください:pray:

2023-07-08 02:44 UTC, urimaro commented on _pages/touristic-autism_intro.md
> +*Translated by Satomi Nishiyama, [nyancat3](https://github.com/nyancat3)*
他のページにならって、`Created by ..` の行に記載してください:pray:

ref. https://railsgirls.jp/github

2023-07-08 02:44 UTC, urimaro commented on _pages/touristic-autism_intro.md
> +このガイドでは、自閉症に優しいかどうかという観点から、観光地を説明、表示、コメント、そして評価できるようにするシナリオを考えましょう。そのシナリオのために、RailsGirlsガイド基礎のいくつかを統合、適用、そして拡張します。このアプリケーションは、自閉症の大人を旅行中にサポートするために、 [Galway Autism Partnership](https://galwayautismpar
`for the scenario` を訳すのがむずかしいですね

secnarioには状況、計画といった意味合いがあるようなので、以下のような訳はいかがでしょうか

* このガイドは **以下を想定して** RailsGirlsガイドの基礎的なものをいくつか統合、適用し、そして拡張しています: 自閉症に優しいかどうかという観点から、観光地を説明、表示、コメント、そして評価できるようにする

※ `**` が漏れてしまっていたようなので追加しています

2023-07-08 02:44 UTC, urimaro commented on _pages/touristic-autism_intro.md
> +統合されて適用された基礎ガイドは、[Ruby on Rails Tutorial](https://www.railstutorial.org/book)、[はじめてのアプリを作る](/app)、そして [CarrierWave を使ってサムネイルを作ってみよう](/thumbnails)、[Devise で認証機能を追加](/devise)、[HTML & CSS を使ってデザインしてみよう]
> 統合されて適用された基礎ガイドは…です。

ひっくり返したほうがわかりやすいかもしれません
また、各コンテンツの紹介は別の文にしてしまっても良いかもしれません

* このガイドには、[Ruby on Rails Tutorial](https://www.railstutorial.org/book)、[はじめてのアプリを作る](/app)、[CarrierWave を使ってサムネイルを作ってみよう](/thumbnails)、[Devise で認証機能を追加](/devise)、[HTML & CSS を使ってデザインしてみよう](/design)、[OpenShiftでアプリを公開する](/openshift/)、[コメント機能を追加しよう](/commenting) のチュートリアルといった基礎的なガイドを統合、適用しています。
* 以下の基礎的なガイドを統合、適用しています: [Ruby on Rails Tutorial](https://www.railstutorial.org/book)、[はじめてのアプリを作る](/app)、[CarrierWave を使ってサムネイルを作ってみよう](/thumbnails)、[Devise で認証機能を追加](/devise)、[HTML & CSS を使ってデザインしてみよう](/design)、[OpenShiftでアプリを公開する](/openshift/)、[コメント機能を追加しよう](/commenting) のチュートリアル。
* 統合、適用した基礎的なガイドは以下のとおりです: [Ruby on Rails Tutorial](https://www.railstutorial.org/book)、[はじめてのアプリを作る](/app)、[CarrierWave を使ってサムネイルを作ってみよう](/thumbnails)、[Devise で認証機能を追加](/devise)、[HTML & CSS を使ってデザインしてみよう](/design)、[OpenShiftでアプリを公開する](/openshift/)、[コメント機能を追加しよう](/commenting) のチュートリアル。


個人的な意見なのでスルーしても構いません

2023-07-08 02:44 UTC, urimaro commented on _pages/touristic-autism_intro.md
> +* 評価機能を準備する
単純に「評価機能」「リソースの評価機能」で良さそうに思いました

2023-07-08 02:44 UTC, urimaro commented on _pages/touristic-autism_intro.md
> +* TDD使用ガイド
TDDは開発手法なので「使う」という言葉は少し違和感を感じました
以下のような訳はいかがでしょうか

* TDDで開発するためのガイド

2023-07-08 02:44 UTC, urimaro commented on _pages/touristic-autism_intro.md
> +* 認証ユーザー（デバイス経由）の権限設定
`Resource Raging` の訳に合わせて「機能」という言葉をつけると、統一感が出て読みやすくなりそうだと思いました
個人的な意見なのでスルーしても構いません

2023-07-08 02:44 UTC, urimaro commented on _pages/touristic-autism_intro.md
> +* Guide 0: [Ruby、Rails、コンソール、テキストエディターについての便利なチートシート](https://www.pragtob.info/rails-beginner-cheatsheet/)
ここは本家を更新しないとですね

2023-07-08 02:44 UTC, urimaro commented on _pages/touristic-autism_intro.md
> +* Guide 1: [Heroku に Rails アプリを deploy しよう](/heroku) / [OpenShiftでアプリを公開する](/openshift) / [anyninesを使用してインターネットに公開しよう!](/anynines) / [Put your app online with Trucker.io](/trucker)
オリジナルの著者名が抜けてしまっているようですが、意図的でしょうか？

2023-07-08 02:44 UTC, urimaro commented on _pages/touristic-autism_intro.md
> +全段階を取り消して最初の状態に戻すには、次のコマンドを使えます。
> 全段階を

「すべてを」のほうが自然かなと思いました
個人的な意見なのでスルーしても構いません

2023-07-08 02:44 UTC, urimaro commented on _pages/touristic-autism_intro.md
> +ご想像の通り、0に他の数字を代入すると、そのバージョン番号までマイグレーションされます。このバージョン番号は、マイグレーションを順番に並べたときの番号となります。
> …0に他の数字を代入すると

「0の代わりに」のほうが自然かなと思いました
個人的な意見なのでスルーしても構いません

> マイグレーションを順番に並べたときの番号となります

何の順番なのか補足するとわかりやすくなりそうに思いました
また「なります」は「です」と言い切ったほうが自然かなと思いました

* マイグレーションを実行順に並べたときの番号です
* マイグレーションを実行順に並べたときの順番です

2023-07-08 02:44 UTC, urimaro commented on _pages/touristic-autism_intro.md
> +次のコマンドを入力することで、データベースを直接閲覧できます (sqlite3の場合は、その後 ".quit " を入力すると終了します) 。
> その後 ".quit" を…

`rails db` の後で入力することはわかると思うので「その後」はなくても良いのかなと思いました
個人的な意見なのでスルーしても構いません

2023-07-08 02:44 UTC, urimaro commented on index.html
> +    <p>(デバイスを用いて) 認証されたユーザーが、自閉症に優しいかどうかという観点から、観光地の説明やコメント、評価をできるようにします。自閉症の大人を旅行中に支援するのが目的です。</p>
> (デバイスを用いて) 認証されたユーザーが

`)` の後の空白は不要かなと思いました

> 観光地の説明やコメント、評価をできるようにします

動作として訳すと読みやすくなるかもしれないと思いました
個人的な意見なのでスルーしても構いません

* 自閉症に優しいかという観点で観光地を説明したり、コメントしたり、評価できるようにします

> 自閉症の大人を

意味はそのとおりだと思うのですが、表現としてちょっと違和感を感じました
`adults` は訳さなくても良いかもしれません
個人的な意見なのでスルーしても構いません

* 旅行中の自閉症の人たちを支援するのが目的です
* 旅行中の成人した自閉症の人たちを支援するのが目的です

2023-07-08 02:44 UTC, urimaro commented on _pages/touristic-autism_intro.md
> +### [*3.* モデルを準備する](/touristic-autism_resource-modeling)
「リソースのモデリング」で良いように思いました

2023-07-08 02:44 UTC, urimaro commented on _pages/touristic-autism_intro.md
> +### [*4.* 評価機能を準備する](/touristic-autism_resource-rating)
18行目と同様です

2023-07-08 02:44 UTC, urimaro commented on _pages/touristic-autism_intro.md
> +### [*6.* イメージのアップロードとサムネイル](/touristic-autism_image-upload)
以下のガイドと関係ある内容だと思うので「画像」でそろえたほうが良いかもしれません

* [画像アップロード機能を追加しよう](https://railsgirls.jp/uploads)

個人的な意見なのでスルーしても構いません

2023-07-08 05:43 UTC, nyancat3 commented on _pages/touristic-autism_intro.md
> +* Guide 1: [Heroku に Rails アプリを deploy しよう](/heroku) / [OpenShiftでアプリを公開する](/openshift) / [anyninesを使用してインターネットに公開しよう!](/anynines) / [Put your app online with Trucker.io](/trucker)
英語版で以下の通り著者名があったりなかったりすることと、
```
Guide 1: [Put your app online with Heroku by Terence Lee](https://guides.railsgirls.com/heroku) / [Put your app online with OpenShift by Katie Miller](https://guides.railsgirls.com/openshift) / [Put your app online with anynines](https://guides.railsgirls.com/anynines) / [Put your app online with Trucker.io](https://guides.railsgirls.com/trucker)
```
日本語版のタイトルに合わせる際に不要かと思い書いていませんでした。念のため追加します！

2023-07-08 05:48 UTC, nyancat3 commented on _pages/touristic-autism_intro.md
> +* 評価機能を準備する
直感的にはそう見えるのですが、今回翻訳したページの各 `Resource` は、リンク先も読んで判断すると名詞でなく動詞(準備する、提供する)として使われていることが分かったためこの翻訳としています！

2023-07-08 05:48 UTC, nyancat3 commented on _pages/touristic-autism_intro.md
> +### [*3.* モデルを準備する](/touristic-autism_resource-modeling)
https://github.com/railsgirls-jp/railsgirls.jp/pull/727#discussion_r1257054967

2023-07-08 05:48 UTC, nyancat3 commented on _pages/touristic-autism_intro.md
> +### [*4.* 評価機能を準備する](/touristic-autism_resource-rating)
https://github.com/railsgirls-jp/railsgirls.jp/pull/727#discussion_r1257054967

2023-07-08 05:53 UTC, nyancat3 commented
@urimaro レビューありがとうございます、修正いたしました！ [e9f4b89](https://github.com/railsgirls-jp/railsgirls.jp/pull/727/commits/e9f4b8976b5dbbdb4cdf5456e66e40583c8cefdc)

2023-07-08 06:00 UTC, nyancat3 commented on _pages/touristic-autism_intro.md
> +このガイドでは、自閉症に優しいかどうかという観点から、観光地を説明、表示、コメント、そして評価できるようにするシナリオを考えましょう。そのシナリオのために、RailsGirlsガイド基礎のいくつかを統合、適用、そして拡張します。このアプリケーションは、自閉症の大人を旅行中にサポートするために、 [Galway Autism Partnership](https://galwayautismpar
ありがとうございます、シナリオという言葉自体はあると理解の助けになるかと思いましたので、アイディア頂いた `想定` と組み合わせて修正いたしました。 `**` も修正済みです。

2023-07-10 00:01 UTC, urimaro commented on _pages/touristic-autism_intro.md
> +* 評価機能を準備する
私も以下のリンク先で、どのように `resource` が使われているのかを見てみたのですが、`routes.rb` で指定したりするリソースという意味かなと思ったのでした

* [Resource Modeling](https://guides.railsgirls.com/touristic-autism_resource-modeling)
* [Resource Rating](https://guides.railsgirls.com/touristic-autism_resource-rating)

どの表現から「準備する、提供する」と判断されましたか？

2023-07-10 00:05 UTC, urimaro commented
確認しやすくするために、コメントを `Unresolve` しますね:pray:

2023-07-10 10:22 UTC, nyancat3 commented on _pages/touristic-autism_intro.md
> +* 評価機能を準備する
ご確認ありがとうございます。例えば [Resource Modeling](https://guides.railsgirls.com/touristic-autism_resource-modeling) では、ページ全体で以下のようにモデル(=リソース)を準備/提供する説明となっていると思います。

> Let’s generate our first resource: user and require its authentication.

> view our second resource: “touristic places”.

これらの文で `Resource` は名詞ですが、model = resource として扱われていると思います。リソース = 評価機能、リソース = モデル であると読み取れるため `リソースの評価機能`、 `リソースのモデリング` と訳すのは個人的に違和感がありました。

また同ページ内のサブセクションでも`Resource` は動詞として使われていると思います

> Resource Associations

> Resource Field Validation

しっくりこないようでしたら、ご提案通りシンプルに `評価機能` と訳します！リソーシングする、という日本語は馴染みがないので提供/準備する、としましたがややこしかったかも知れませんね。

2023-07-14 00:27 UTC, urimaro commented on _pages/touristic-autism_intro.md
> +* 評価機能を準備する
> Let’s generate our first resource: user and require its authentication.
> view our second resource: “touristic places”.

これらの文からは `resource` が動詞として使われているとは思えませんでした

> Resource Associations
> Resource Field Validation

これらの `Resource` は動詞ではないのではないでしょうか
`Resource Associations` はRailsGudeの [Active Record Associations](https://guides.rubyonrails.org/association_basics.html) 、 [Active Record Validations](https://guides.rubyonrails.org/active_record_validations.html) のActive Recordとほぼ同じ意味で使われていると思っています
また、nancat3 さんのおっしゃるとおり、今回翻訳していただいたガイドでは「model = resource として扱っている」と考えて良いと思います(※)
これらのことから `Resource Associations` は「モデルの関連(Active Recordの関連)」を意味していて、動詞ではないのではないかと思いました

`Resource Field Validation` も同様に考えられると思います
「モデルのフィールド(属性)に対するバリデーション」という意味ではないでしょうか？

※
モデルには処理を実装しますし、複数のモデルで組み立てられるリソースもあるので、著者が「model = resource」として扱っていることに、ちょっと違和感はあります
また、厳密には「関連した結果」がリソースなので `Resource Associations` も違和感があります
それでも、著者が言いたいことは十分にわかりますし、「RailsGirlsガイド」なので細かいことよりも、わかりやすさ、イメージしやすさを優先しているんだろうなと思っています

---

@maimux2x 
maimux2sさんは、どう思われますか？

2023-07-14 02:45 UTC, maimux2x commented on _pages/touristic-autism_intro.md
> +* 評価機能を準備する
> The extension comprises of the following new features:
> TDD using Guide
Resource Rating
Authenticated User (via devise) permission setting

この部分であっておりますでしょうか？
「この拡張機能は以下の新機能で構成されています」の流れに続くリストである点と関連するリンク先を読んだ結果、gohさんが提案されている
- 「評価機能」
- 「リソースの評価機能」
の日本語で今回はいいのではないかなと思いました！

2023-07-14 03:27 UTC, nyancat3 commented on _pages/touristic-autism_intro.md
> +* 評価機能を準備する
`評価機能` に修正しますね！

2023-07-14 11:02 UTC, nyancat3 commented on _pages/touristic-autism_intro.md
> +### [*4.* 評価機能を準備する](/touristic-autism_resource-rating)
[51bf4be](https://github.com/railsgirls-jp/railsgirls.jp/pull/727/commits/51bf4beb901d3544aa2b4169274f5f89a558c4f5) で対応済み

2023-07-14 11:02 UTC, nyancat3 commented on _pages/touristic-autism_intro.md
> +### [*3.* モデルを準備する](/touristic-autism_resource-modeling)
[51bf4be](https://github.com/railsgirls-jp/railsgirls.jp/pull/727/commits/51bf4beb901d3544aa2b4169274f5f89a558c4f5) で対応済み

2023-07-14 11:02 UTC, nyancat3 commented on _pages/touristic-autism_intro.md
> +* 評価機能を準備する
[51bf4be](https://github.com/railsgirls-jp/railsgirls.jp/pull/727/commits/51bf4beb901d3544aa2b4169274f5f89a558c4f5) で対応済み

2023-07-15 03:10 UTC, urimaro commented on _pages/touristic-autism_intro.md
> +* 評価機能を準備する
ありがとうございます:bow:
確認しますー

2023-07-15 03:14 UTC, urimaro approved these changes
色々と対応いただき、ありがとうございました
LGTM:+1:です

2023-07-15 03:51 UTC, merged