Write a little game in Rubyを翻訳した
railsgirls-jp/railsgirls.jp pull request #742
Opened 2023-10-16 13:26 UTC by maimux2x

2023-10-18 13:22 UTC, maimux2x commented
gemのバージョンが古そうなため確認する

2023-10-29 05:51 UTC, maimux2x commented
ガイド上部に説明が古い旨の注意書きを追記しました。

2023-11-03 06:33 UTC, urimaro requested changes
コメントしました
確認をお願いします:pray:

2023-11-03 06:33 UTC, urimaro commented on _pages/ruby-game.md
> +[gosu](http://www.libgosu.org/)は 2D ゲーム開発ライブラリです。Gosu は 2D グラフィックスやテキスト（3D ハードウェアによる高速化）、音源のサンプルや音楽、キーボード、マウス、ゲームパッド/ジョイスティックの入力に対して、使いやすくゲームに適したインタフェースを提供しているという特徴があります。また，RMagick、Chipmunk、OpenGL 一体
> …音源のサンプルや音楽、キーボード、…

`as well as` とあるので、「…音楽だけでなく、キーボード、…」としても良いかも知れません
個人的な意見なので、スルーしても構いません

> また，RMagick、Chipmunk、OpenGL 一体化したデモも含まれています

細かいですが「，」は「、」で統一したほうが良さそうです
また、「OpenGL」のあとの「と」が抜けてしまっているようです

- …OpenGL と一体化…

2023-11-03 06:33 UTC, urimaro commented on _pages/ruby-game.md
> +続いて`ruby CptnRuby.rb`
「続いて」のあとの半角スペースが抜けてしまっているかもしれません
統一しようとしているのかなと思ったので指摘しましたが、スルーしても構いません

なお、L21の「もしくは、」のあとは「、」のあとなので、あえて半角スペースを入れなかったのかなと思っています
他の部分を見直すかどうかの判断もおまかせします😊

2023-11-03 06:33 UTC, urimaro commented on _pages/ruby-game.md
> +@cur_image.draw(@x + offs_x, @y - 49, 0, factor, 1.0)
インデントがなくなってしまっているようです

2023-11-03 06:33 UTC, urimaro commented on _pages/ruby-game.md
> +... という具体的な内容が書かれています。 Game クラスに含まれる`def`はメソッドです。 ここでは、プログラムがどの命令に従うかを**_定義_**します。以下のスニペットをご覧ください。
> So we have our thing going on.

難しいですね
(感想です)
どう訳すと良いか思い浮かびませんでした

> `**_定義_**`

`**定義**` で良さそうです

2023-11-03 06:33 UTC, urimaro commented on _pages/ruby-game.md
> +少し遊んでみませんか？ `game.rb` の内容を新しい `.rb` ファイルにコピーしてください。 好みの名前で命名して保存しましょう。 そして、ゲーム内のいくつかの要素を変更して、ターミナルで実行して変更内容を確認してみてください。
> 名前で命名して

重複している感じがするので「名前で」だけでも良さそうです
個人的な意見なのでスルーしても構いません

2023-11-03 06:33 UTC, urimaro commented on _pages/ruby-game.md
> +end
インデントがなくなってしまっているようです

2023-11-03 06:33 UTC, urimaro commented on _pages/ruby-game.md
> +そして`Game.new.show`を見てください。これは新しいインスタンスを作成します。メモリは持っておらず、ゲームで詰まったときには新しいゲームを始めることができます。楽しんでください！
> メモリは持っておらず

「has no memory」は「何も保存していない」という意味で使っているんじゃないかなと思いました

2023-11-03 06:33 UTC, urimaro commented on _pages/ruby-game.md
> +使用されている音声は [Matthew Klingensmith (www.matthewklingensmith.com)](http://opengameart.org/content/matts-creative-commons-music)で入手できます。
> 音声は

冒頭の説明と合わせて「音源」としても良いかもしれません
個人的な意見なので、スルーしても構いません

2023-11-05 12:33 UTC, maimux2x commented on _pages/ruby-game.md
> +[gosu](http://www.libgosu.org/)は 2D ゲーム開発ライブラリです。Gosu は 2D グラフィックスやテキスト（3D ハードウェアによる高速化）、音源のサンプルや音楽、キーボード、マウス、ゲームパッド/ジョイスティックの入力に対して、使いやすくゲームに適したインタフェースを提供しているという特徴があります。また，RMagick、Chipmunk、OpenGL 一体
@urimaro 
レビューありがとうございます！
こちら修正いたしました🙏

2023-11-05 12:34 UTC, maimux2x commented on _pages/ruby-game.md
> +続いて`ruby CptnRuby.rb`
こちら見落としなため修正しました！

2023-11-05 12:35 UTC, maimux2x commented on _pages/ruby-game.md
> +@cur_image.draw(@x + offs_x, @y - 49, 0, factor, 1.0)
こちらも修正しました🙏

2023-11-05 12:36 UTC, maimux2x commented on _pages/ruby-game.md
> +... という具体的な内容が書かれています。 Game クラスに含まれる`def`はメソッドです。 ここでは、プログラムがどの命令に従うかを**_定義_**します。以下のスニペットをご覧ください。
VSCodeの拡張機能で`_`が入るようになってしまっていました・・・こちらも修正しました✨

2023-11-05 12:36 UTC, maimux2x commented on _pages/ruby-game.md
> +少し遊んでみませんか？ `game.rb` の内容を新しい `.rb` ファイルにコピーしてください。 好みの名前で命名して保存しましょう。 そして、ゲーム内のいくつかの要素を変更して、ターミナルで実行して変更内容を確認してみてください。
確かに重複していますね。
「名前で」だけに修正しました！

2023-11-05 12:37 UTC, maimux2x commented on _pages/ruby-game.md
> +end
こちらも修正しました🙏

2023-11-05 12:38 UTC, maimux2x commented on _pages/ruby-game.md
> +そして`Game.new.show`を見てください。これは新しいインスタンスを作成します。メモリは持っておらず、ゲームで詰まったときには新しいゲームを始めることができます。楽しんでください！
「保存はしていないため」に修正してみました。
もし他に良さそうな訳がありましたらアイディアをいただけると幸いです🙇🏻‍♀️

2023-11-05 12:39 UTC, maimux2x commented on _pages/ruby-game.md
> +使用されている音声は [Matthew Klingensmith (www.matthewklingensmith.com)](http://opengameart.org/content/matts-creative-commons-music)で入手できます。
musicなので「音源」の方が良さそうですね。
修正しました！

2023-11-05 15:00 UTC, urimaro approved these changes
LGTM:+1:です！

2023-11-05 15:01 UTC, merged