Rakefileの内容を修正し、READMEも合わせて修正した
railsgirls-jp/railsgirls.jp pull request #755
Opened 2023-11-12 06:02 UTC by maimux2x

## issue
#750

## やったこと
### 1. ガイドを作成するrakeコマンドを修正
ガイドを作成するrakeコマンドが `post` を指定する形になっていて何を作成するコマンドかが判断しにくくなっていたため、明示的に`guide`を指定するように修正しました。

```
 bundle exec rake guide title="my fabulous guide"
```

### 2. ドメイン直下のページを作成するコマンドを追加
`CoC` や `About` のようなドメイン直下のページを新規で作成するコマンドがなかったため追加しました。

```
$ bundle exec rake original_content title="new original content"
```

`_pages-jp` 配下に新規ファイルが作成されます。
ファイル作成時には以下の項目がデフォルトで追加されるようにしてあります。

```
---
layout: original_content
title: "my fabulous post"
permalink: 
---
```

### 3. ディレクトリ+ファイルを作成するコマンド名を修正
独立したページを作成するコマンドを実行すると、「ディレクトリ+ファイル」が生成されるため、コマンド名もそれが明示的にわかるように修正しました。

```
$ bundle exec rake directory_with_page name="something"
```

### 4. READMEを修正
1~3に合わせてREADMEを修正しました。

2023-11-13 00:02 UTC, urimaro commented
> ## issue
> #750

issueと紐付けるコメントを追加しておくと、pull requestがmergeされるとissueもcloseされるので便利です
「どんなコメントを追加するとissueと紐づくのか」は以下を参照してみてください

- [Pull RequestをIssueにリンクする](https://docs.github.com/ja/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

上記にはコメントで紐付けるのではなく、手動で紐付ける方法も説明されているので、そちらも参考になると思います

2023-11-13 01:11 UTC, urimaro requested changes
コメントしました
確認をお願いします:pray:
![imo](https://img.shields.io/badge/imo-green.svg) はスルーして構いません
また、別のissue、PRを作って対応しても良いと思います😊

2023-11-13 01:11 UTC, urimaro commented on Rakefile
> +end # task :original_contents
![imo](https://img.shields.io/badge/imo-green.svg)
以下のタスクはほぼ同じことをしていると思います

- guide
- blog
- original_content

同じ処理をメソッドに抽出してみてはどうでしょうか？(※1)
その際、以下の記事が参考になるかもしれません(※2)

- [rails、Rakefile内で共通の変数やメソッドを書く場所について](https://teratail.com/questions/140119)

※1 `directory_with_page` も似ていますが、まずは上記3つのタスクだけでも良いと思います
※2 高橋さんが回答しているのもポイントですね

2023-11-13 01:11 UTC, urimaro commented on Rakefile
> +task :directory_with_page do
![nits](https://img.shields.io/badge/nits-orange.svg)
タスク名が変わったので、L129のコメントも更新したほうが良さそうです

2023-11-13 01:11 UTC, urimaro commented on Rakefile
> +desc "Begin a new guide in #{CONFIG['pages']}"
![nits](https://img.shields.io/badge/nits-orange.svg)
他のタスクにならったのだと思いますが、コメントになっている `Usage` も `desc` の中に記述したほうが良いと思います
`desc` に書くことで、`rake -D` で `desc` の内容をすべて表示できるようになります

```
desc <<~DESK
  Begin a new guide in #{CONFIG['pages']}
  Usage: rake guide title="A Title" [date="2012-02-09"]
DESK
```

2023-11-13 01:11 UTC, urimaro commented on README.md
>  ## ページを追加
![must](https://img.shields.io/badge/must-magenta.svg)
#751 をmergeしたので `git rebase` をお願いします:pray:

2023-11-13 01:11 UTC, urimaro commented on README.md
> +
![imo](https://img.shields.io/badge/imo-green.svg)
「どんなときにどのタスクを使うのか」がわかるよう、過去のイベントのページを紹介するなどして、`original_content` タスクのように、もう少し具体的に説明しても良いかもしれません
例えば…

> 〇〇のようなイベントのページを作る場合、

2023-11-14 13:08 UTC, maimux2x commented on Rakefile
> +end # task :original_contents
ありがとうございます！
確かにメソッド抽出するのも良さそうです✨
修正してみます〜！

2023-11-15 12:57 UTC, maimux2x commented on Rakefile
> +task :directory_with_page do
こちら見落としていました🙇🏻‍♀️
修正します！

2023-11-15 12:58 UTC, maimux2x commented on README.md
>  ## ページを追加
rebase対応いたしました👍

2023-11-15 13:09 UTC, maimux2x commented on Rakefile
> +desc "Begin a new guide in #{CONFIG['pages']}"
確かにですね👀
各タスクのコメントを`desc`に含めるようにします！

2023-11-15 13:10 UTC, maimux2x commented on Rakefile
> +end # task :original_contents
こちらですが、修正範囲が大きくなりそうなため、別issueに切り出して対応します🙏

2023-11-15 13:14 UTC, maimux2x commented on README.md
> +
ありがとうございます！
こちらもタイトルを修正します✨

2023-11-16 08:04 UTC, urimaro commented on Rakefile
> +end # task :original_contents
> 修正範囲が大きくなりそうなため、別issueに切り出して対応します🙏

良いと思います！

2023-11-16 08:05 UTC, urimaro commented on Rakefile
> +task :directory_with_page do
確認しました〜

2023-11-16 08:21 UTC, urimaro approved these changes
TYPOを1つ見つけました
確認をお願いします :pray:
approveしておきますので、修正したら、ご自身でmergeしてしまって 👌 です

2023-11-16 08:21 UTC, urimaro commented on Rakefile
> +  Create a new directroy and page.
![nits](https://img.shields.io/badge/nits-orange.svg)
TYPOですね😉

- directroy
- directory

2023-11-19 12:35 UTC, maimux2x commented
@urimaro 
`directory_with_page` のタスクで`.md`や`.html`の拡張子付きの引数を渡すとどのディレクトリにも属さない空ファイルを作成できることを見落としていました・・・
空ファイルが作成されても結果的にどこかのディレクトリ配下に移動させないといけないため、ファイルのみが作成される処理は削除して修正しようと思います。
他に見落としがないか含めて確認次第改めて本PRでレビュー依頼いたします🙏

2023-11-20 01:24 UTC, urimaro commented
@maimux2x 

> `directory_with_page` のタスクで`.md`や`.html`の拡張子付きの引数を渡すとどのディレクトリにも属さない空ファイルを作成できることを見落としていました

この事象について、もう少し詳しく知りたいところですが、この処理は以前から存在しているので、別のissueを作って対応しても良さそうに思います

引数を指定するときに `name=` を指定しないとサブタスクとして認識され「そんなタスクはない」と怒られるのですが、その際、`./new-page.md` が作成されることは確認しました
バグなんじゃないかなと思っています
＜ 拡張子の有無を確認するタイミングが良くなさそう

2023-11-20 13:38 UTC, maimux2x commented
@urimaro 
ご確認いただき、ありがとうございます🙏
`.new-page.md` が作成される件は今回の修正で発生したものではないため、一旦こちらのPRはマージして別issueを立てた上で詳細をまとめるようにいたします！

2023-11-20 13:48 UTC, merged