Ease up development with Phusion Passengerを翻訳した
railsgirls-jp/railsgirls.jp pull request #758
Opened 2023-11-14 12:02 UTC by maimux2x

## issue
#746

## 概要
https://railsgirls.jp/passenger
上記ガイドを翻訳しました。

【Let’s check if that worked】のセクションに含まれる「Big (friendly, promised!) brother is watching you.」は英語特有のジョークで適切な日本語がないため訳出していません。
![FireShot Capture 001 - Rails Girls - Japanese - localhost](https://github.com/railsgirls-jp/railsgirls.jp/assets/76797372/a894f4ac-9ca2-4289-bb3a-ee7390465e70)

2023-11-16 08:39 UTC, urimaro commented on _pages/passenger.md
> +# Phusion Passengerでスムーズに開発しよう
「Ease up」を「スムーズに」と訳すのは良いですね！

2023-11-16 09:59 UTC, urimaro requested changes
翻訳していただき、ありがとうございます！:clap:
コメントしていますので確認をお願いします:pray:
![imo](https://img.shields.io/badge/imo-green.svg) は個人的な意見なのでスルーしても:ok_hand:です
(`imo` =  `in my opinion`)

2023-11-16 09:59 UTC, urimaro commented on _pages/passenger.md
> +「rails server」自体はアプリケーションサーバーではなく、単なる小さなラッパーで、アプリをアプリケーションサーバーで起動させるものです。人々は「rails server」を本番環境（他の人がアクセスしてアプリを使用できる場所）では使用しません。Passengerなどのアプリケーションサーバーを使用します。
![imo](https://img.shields.io/badge/imo-green.svg)

> 人々は「rails server」を..

この場合、`People` は不特定多数の人を意味していると思うので訳さなくても良さそうに思いました

---

![ask](https://img.shields.io/badge/ask-blue.svg)
英文の区切りで改行したり、しなかったりしているのは何か狙いがあったりしますか？

2023-11-16 09:59 UTC, urimaro commented on _pages/passenger.md
> +NginxとApacheはwebサーバーです。 それらはHTTPトランザクションの処理と静的ファイルの提供を行います。アプリケーションサーバーは、RubyアプリがHTTPで通信することを可能にします。Rubyのアプリケーション（そしてRailsのようなフレームワーク）自体はHTTP通信ができません。通常のプロダクションスタックでは、ウェブサーバーとしてNginxまたはApache、アプリケーショ
![imo](https://img.shields.io/badge/imo-green.svg)

> 通常のプロダクションスタックでは、..

「通常」と訳すと他の構成が特殊なように聞こえるかもと思いました
「典型的な」とか「よくある」のほうが「色々な構成が考えられるけれど、今はこの構成が多い」のように、「そうしたほうが良い」という圧が薄まるかもと思いました
かなり主観が入っているので、スルーしても結構です

2023-11-16 09:59 UTC, urimaro commented on _pages/passenger.md
> + `gem "passenger", ">= 5.0.25", require: "phusion_passenger/rack_handler"`
![imo](https://img.shields.io/badge/imo-green.svg)
先頭にスペースが入っているようです
削除するかどうかはお任せします

2023-11-16 09:59 UTC, urimaro commented on _pages/passenger.md
> +Passengerはクラッシュしたプロセスを再起動し、トラフィックをプロセス間で負荷分散し、トラフィックの増減に応じてプロセスをスケーリングして、より多くのトラフィックを処理したり、リソースを節約したりします。これはすべて自動的に処理され、コードで何かを指定する必要はありません！ 今はあまり意味がないかもしれませんが、将来の開発者は私たちに感謝するでしょう。
![imo](https://img.shields.io/badge/imo-green.svg)

> ..スケーリングして..

「スケールする」の意味がわからない人のために「増やしたり、減らしたりして」のように「スケール」という言葉を使わないほうが良いかもしれません

2023-11-16 09:59 UTC, urimaro commented on _pages/passenger.md
> +今後のために、`passenger-config restart-app`コマンドを使ってアプリケーションを再起動することができます。これは Passenger を停止して起動するよりも便利で、2つのコマンドが必要です。
![must](https://img.shields.io/badge/must-magenta.svg)

> 2つのコマンドが必要です

`which requires two commands` は `stopping and starting Passenger` を説明していると思いました
なので、以下のような感じでいかがでしょうか？

- Passengerを停止して起動するのに2つのコマンドが必要なこと比べて。これは便利です
- Passengerを停止して起動するのに2回コマンドを実行しなければいけないことと比べると、これは便利です

2023-11-16 09:59 UTC, urimaro commented on _pages/passenger.md
> +Passenger は `tmp/always_restart.txt` というマジックファイルもサポートしています。このファイルを使うと、Passenger はリクエストのたびにアプリケーションを再起動します。こうすることで、再起動コマンドを頻繁に起動する必要がなくなります。
![imo](https://img.shields.io/badge/imo-green.svg)

> 再起動コマンドを頻繁に起動する..

起動するが重複しているので「頻繁に実行する」というのはいかがでしょうか？

2023-11-16 09:59 UTC, urimaro commented on _pages/passenger.md
> +迷いましたか？ Phusion Passengerには初心者向けのガイドを含む詳細なドキュメンテーションがあります。
![imo](https://img.shields.io/badge/imo-green.svg)

> ドキュメンテーション

「ドキュメント」で良いかもしれません

2023-11-18 07:14 UTC, maimux2x commented on _pages/passenger.md
> +「rails server」自体はアプリケーションサーバーではなく、単なる小さなラッパーで、アプリをアプリケーションサーバーで起動させるものです。人々は「rails server」を本番環境（他の人がアクセスしてアプリを使用できる場所）では使用しません。Passengerなどのアプリケーションサーバーを使用します。
ありがとうございます！
「人々は」の部分は削除しました👍
改行は一文ずつ訳す中で意図せず加えてしまっていたため、こちらも修正しました🙏

2023-11-18 07:16 UTC, maimux2x commented on _pages/passenger.md
> +NginxとApacheはwebサーバーです。 それらはHTTPトランザクションの処理と静的ファイルの提供を行います。アプリケーションサーバーは、RubyアプリがHTTPで通信することを可能にします。Rubyのアプリケーション（そしてRailsのようなフレームワーク）自体はHTTP通信ができません。通常のプロダクションスタックでは、ウェブサーバーとしてNginxまたはApache、アプリケーショ
ここは「典型的」か「通常」かで迷った部分でした😅
「よくある」がニュアンス的に良さそうだなと思ったため修正しました！

2023-11-18 07:17 UTC, maimux2x commented on _pages/passenger.md
> + `gem "passenger", ">= 5.0.25", require: "phusion_passenger/rack_handler"`
意図的に改行を入れて、その際にスペースが入ってしまったようです😅
スペースは削除しました！

2023-11-18 07:19 UTC, maimux2x commented on _pages/passenger.md
> +Passengerはクラッシュしたプロセスを再起動し、トラフィックをプロセス間で負荷分散し、トラフィックの増減に応じてプロセスをスケーリングして、より多くのトラフィックを処理したり、リソースを節約したりします。これはすべて自動的に処理され、コードで何かを指定する必要はありません！ 今はあまり意味がないかもしれませんが、将来の開発者は私たちに感謝するでしょう。
ありがとうございます！
より伝わりやすいことを優先して修正しました👍

2023-11-18 07:24 UTC, maimux2x commented on _pages/passenger.md
> +今後のために、`passenger-config restart-app`コマンドを使ってアプリケーションを再起動することができます。これは Passenger を停止して起動するよりも便利で、2つのコマンドが必要です。
意味が通ってない文章になっていました😅
ありがとうございます🙏
修正しました〜！

2023-11-18 07:25 UTC, maimux2x commented on _pages/passenger.md
> +Passenger は `tmp/always_restart.txt` というマジックファイルもサポートしています。このファイルを使うと、Passenger はリクエストのたびにアプリケーションを再起動します。こうすることで、再起動コマンドを頻繁に起動する必要がなくなります。
こちらも修正しました👍

2023-11-19 09:41 UTC, urimaro approved these changes
細かいところまで対応していただき、ありがとうございます！
コメントしましたが、approveしておきますので、対応する/しないにかかわらず、ご自身でmergeしてしまって 👌 です

2023-11-19 09:41 UTC, urimaro commented on _pages/passenger.md
> +NginxとApacheはwebサーバーです。 それらはHTTPトランザクションの処理と静的ファイルの提供を行います。アプリケーションサーバーは、RubyアプリがHTTPで通信することを可能にします。Rubyのアプリケーション（そしてRailsのようなフレームワーク）自体はHTTP通信ができません。よくあるプロダクションスタックでは、ウェブサーバーとしてNginxまたはApache、アプリケーシ
![imo](https://img.shields.io/badge/imo-green.svg)

> プロダクションスタック

意味がわからない人のために「本番環境」「本番環境の構成」のように言い換えたほうが良いかもしれません
後出しで申し訳ないです:bow:

2023-11-19 12:12 UTC, maimux2x commented on _pages/passenger.md
> +NginxとApacheはwebサーバーです。 それらはHTTPトランザクションの処理と静的ファイルの提供を行います。アプリケーションサーバーは、RubyアプリがHTTPで通信することを可能にします。Rubyのアプリケーション（そしてRailsのようなフレームワーク）自体はHTTP通信ができません。よくあるプロダクションスタックでは、ウェブサーバーとしてNginxまたはApache、アプリケーシ
ありがとうございます！
修正の上、マージするようにします🙏

2023-11-19 12:24 UTC, merged