Add Rails Girls matsue 5th report
railsgirls-jp/railsgirls.jp pull request #762
Opened 2023-11-30 13:10 UTC by ishikawa999

2023/11/11に開催したRailsGirls matsue 5thの開催レポートです。
確認をお願いいたします。

執筆者は 槇原さん( @ama3193 )です。プルリクエストの変換やMarkdown形式への変換を私が担当。

2023-12-03 03:20 UTC, thatblue requested changes
確認途中ではあるのですが、取り急ぎtypoかなと思ったところだけコメントさせていただきました！

2023-12-03 03:20 UTC, thatblue commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +5名とも運営は初めてということもあり、不明点ばかり。前回のオーガナイザーへのヒアリングやRails Girls JAPANの皆さまにご協力頂きながら準備をしました。
重箱の隅で申し訳ないのですが、Rails Girls **Japan**(先頭だけ大文字)が正しい表記なので、修正していただけるとうれしいです 🙏

2023-12-03 03:20 UTC, thatblue commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +さらに、スポンサーLTとして、「フィヨルドブートキャンプ」様からの動画LT、そして今年のRuby Biz Prix大賞を受賞された「PIXIV」様からの現地LT（法被を身にまとったLTでした！）、さらに「Tokyo Dev」様は、Rail Girl Matsueのために松江に足を運んで発表してくださったことに感謝申し上げます。
固有名詞の表記ゆれがあるようでしたので、ご確認をお願いしたいです。

- Ruby Biz Prix→Ruby Biz Grand Prix
- PIXIV→サービス名ならpixiv、社名であればピクシブ(もしくはピクシブ株式会社)が正式な表記

2023-12-03 03:20 UTC, thatblue commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +スポンサーの皆さま、コーチの皆さま、そして参加者の皆さまのおかげでRailsGirlsを無事に開催することができました。重ね重ね御礼申し上げます！
これも重箱の隅で申し訳ないのですが、**Rails Girls**(RailsとGirlsの間にスペースを空ける)で表記していただきたいです 🙏

2023-12-03 03:53 UTC, ishikawa999 commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +5名とも運営は初めてということもあり、不明点ばかり。前回のオーガナイザーへのヒアリングやRails Girls JAPANの皆さまにご協力頂きながら準備をしました。
ご指摘いただきありがとうございます。 https://github.com/railsgirls-jp/railsgirls.jp/pull/762/commits/6c380c5cd640f29fb01b0475517e2ee8107752fd で修正しました。

2023-12-03 03:53 UTC, ishikawa999 commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +さらに、スポンサーLTとして、「フィヨルドブートキャンプ」様からの動画LT、そして今年のRuby Biz Prix大賞を受賞された「PIXIV」様からの現地LT（法被を身にまとったLTでした！）、さらに「Tokyo Dev」様は、Rail Girl Matsueのために松江に足を運んで発表してくださったことに感謝申し上げます。
ご指摘いただきありがとうございます。
https://github.com/railsgirls-jp/railsgirls.jp/pull/762/commits/6c380c5cd640f29fb01b0475517e2ee8107752fd で社名に合わせる形で変更しました。

2023-12-03 03:54 UTC, ishikawa999 commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +スポンサーの皆さま、コーチの皆さま、そして参加者の皆さまのおかげでRailsGirlsを無事に開催することができました。重ね重ね御礼申し上げます！
https://github.com/railsgirls-jp/railsgirls.jp/pull/762/commits/6c380c5cd640f29fb01b0475517e2ee8107752fd で修正しました！

2023-12-04 12:48 UTC, emorima requested changes
開催ブログありがとうございます！

「Ruby biz Grand prix」の正式名称の修正と、
お送りした本については、寄贈していただいた鳥井さんと五十嵐さんのお名前も記載をお願いできればと思います！

2023-12-04 12:48 UTC, emorima commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +松江市では、毎年Rubyの最大級のイベントRubyWorld Conferenceが2日間開催され、そのイベントの前日にはRuby biz pixも開催されます。その3日間はRuby色に染まる松江。だったら、「Ruby Week」と題して、Rubyに関連するイベントを色々企画しようと島根県、松江市、Ruby Associationで決まりました。その中で、ぜひ「Rails Girlsを松江で復活
「Ruby biz pix」 となっていますが、「Ruby biz Grand prix」が正しい名称のようです! :medal_sports:

2023-12-04 12:48 UTC, emorima commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +さらに、スポンサーLTとして、株式会社ロッカ様からの動画LT、そして今年のRuby Biz Grand Prix大賞を受賞されたピクシブ株式会社様からの現地LT（法被を身にまとったLTでした！）、さらにTokyoDev株式会社様はRail Girl Matsueのために松江に足を運んで現地LTをしてくださいました。
「Ruby biz Grand prix」が正しい名称みたいです！ :medal_sports: 
https://rubybiz.jp/

2023-12-04 12:48 UTC, emorima commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +残りの工程を進めていきます。やはり、後半もみなさまスムーズに取り組んでくださり、思い思いに自分仕様にカスタマイズするところまで、あっという間に進みました！
ここまでの文章を見ると、参加者の方は、「皆さん」で表現されているみたいなので、
合わせるとよいかもと思いました！

2023-12-04 12:48 UTC, emorima commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +そして仕組みが分かった第２回戦は戦略をチームで練ります。そして、２回目では、最も早く並び替えたチームから今回のスペシャルゲスト江森真由美氏からご提供いただいた本を景品をプレゼント。
お送りした本についてなのですが、
著者の鳥井雪さん、五十嵐邦明さん（おふたりとも、Rails Girls にとても関わりがある方です！）から、
Rails Girls の皆さんでどうぞ、と寄贈頂いているので、
お二人のお名前も掲載お願いしたいです！

2023-12-04 12:57 UTC, thatblue requested changes
すみません、一度修正していただいた後で申し訳ないのですが、一点だけ内容に関するご対応をお願いします 🙏

2023-12-04 12:57 UTC, thatblue commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +Rails Girls は、より多くの女性がプログラミングに親しみ、アイデアを形にできる技術を身に着けるきっかけ作りと手助けをするコミュニティです。2010年にフィンランドのヘルシンキにてリンダ・リウカス氏らによって設立された団体であり、今では世界各国で活動が行われています。
Rails Girlsについてですが、団体と言うよりは「コミュニティ」という方がより実態に沿っているかなと思うので、そちらで表記をお願いします 🙏

2023-12-04 12:58 UTC, thatblue commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +5名とも運営は初めてということもあり、不明点ばかり。前回のオーガナイザーへのヒアリングやRails Girls JAPANの皆さまにご協力頂きながら準備をしました。
ご対応ありがとうございます！修正を確認しました。

2023-12-04 13:00 UTC, thatblue commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +さらに、スポンサーLTとして、株式会社ロッカ様からの動画LT、そして今年のRuby Biz Grand Prix大賞を受賞されたピクシブ株式会社様からの現地LT（法被を身にまとったLTでした！）、さらにTokyoDev株式会社様はRail Girl Matsueのために松江に足を運んで現地LTをしてくださいました。
@ishikawa999 
(すみません、これ私のコメントも間違ってましたね…ごめんなさい)

2023-12-04 13:02 UTC, thatblue commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +さらに、スポンサーLTとして、「フィヨルドブートキャンプ」様からの動画LT、そして今年のRuby Biz Prix大賞を受賞された「PIXIV」様からの現地LT（法被を身にまとったLTでした！）、さらに「Tokyo Dev」様は、Rail Girl Matsueのために松江に足を運んで発表してくださったことに感謝申し上げます。
ご対応ありがとうございます！修正を確認しました。
そして一度に見つけられずに申し訳ないです、これまた重箱の隅で申し訳ないのですが **Rail Girl**(RailsとGirlsのsが抜けている)となっているので、ご確認をお願いします 🙏

2023-12-04 13:02 UTC, thatblue commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +スポンサーの皆さま、コーチの皆さま、そして参加者の皆さまのおかげでRailsGirlsを無事に開催することができました。重ね重ね御礼申し上げます！
ご対応ありがとうございます！こちらも修正を確認しました。

2023-12-04 15:56 UTC, ishikawa999 commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +Rails Girls は、より多くの女性がプログラミングに親しみ、アイデアを形にできる技術を身に着けるきっかけ作りと手助けをするコミュニティです。2010年にフィンランドのヘルシンキにてリンダ・リウカス氏らによって設立された団体であり、今では世界各国で活動が行われています。
https://github.com/railsgirls-jp/railsgirls.jp/pull/762/commits/1b13b407dea2b472ebda6632d31c17c55dbc0485 で修正しました。ご指摘いただきありがとうございます。

2023-12-04 15:57 UTC, ishikawa999 commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +そして仕組みが分かった第２回戦は戦略をチームで練ります。そして、２回目では、最も早く並び替えたチームから今回のスペシャルゲスト江森真由美氏からご提供いただいた本を景品をプレゼント。
> そして、最も早く並び替えたチームから順番に景品をプレゼント。景品はRubyやRailsの勉強に役立つ素敵な本で、それぞれの本の著者でいらっしゃる江森真由美氏、鳥井雪氏、五十嵐邦明氏からご寄贈いただきました。

のように書いてみたのですが、こんな感じで良いでしょうか？

2023-12-04 15:57 UTC, ishikawa999 commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +残りの工程を進めていきます。やはり、後半もみなさまスムーズに取り組んでくださり、思い思いに自分仕様にカスタマイズするところまで、あっという間に進みました！
見直しました！ご指摘いただきありがとうございます。
https://github.com/railsgirls-jp/railsgirls.jp/pull/762/commits/1b13b407dea2b472ebda6632d31c17c55dbc0485

2023-12-04 15:57 UTC, ishikawa999 commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +さらに、スポンサーLTとして、株式会社ロッカ様からの動画LT、そして今年のRuby Biz Grand Prix大賞を受賞されたピクシブ株式会社様からの現地LT（法被を身にまとったLTでした！）、さらにTokyoDev株式会社様はRail Girl Matsueのために松江に足を運んで現地LTをしてくださいました。
正式名称をきちんと確認すべきでした。。ご指摘いただきありがとうございます。修正しました。
https://github.com/railsgirls-jp/railsgirls.jp/pull/762/commits/1b13b407dea2b472ebda6632d31c17c55dbc0485

2023-12-04 15:58 UTC, ishikawa999 commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +松江市では、毎年Rubyの最大級のイベントRubyWorld Conferenceが2日間開催され、そのイベントの前日にはRuby biz pixも開催されます。その3日間はRuby色に染まる松江。だったら、「Ruby Week」と題して、Rubyに関連するイベントを色々企画しようと島根県、松江市、Ruby Associationで決まりました。その中で、ぜひ「Rails Girlsを松江で復活
修正漏れでした。ご指摘いただきありがとうございます。
https://github.com/railsgirls-jp/railsgirls.jp/pull/762/commits/1b13b407dea2b472ebda6632d31c17c55dbc0485

2023-12-04 15:58 UTC, ishikawa999 commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +さらに、スポンサーLTとして、「フィヨルドブートキャンプ」様からの動画LT、そして今年のRuby Biz Prix大賞を受賞された「PIXIV」様からの現地LT（法被を身にまとったLTでした！）、さらに「Tokyo Dev」様は、Rail Girl Matsueのために松江に足を運んで発表してくださったことに感謝申し上げます。
謎のtypoですね。。失礼しました。修正しました。
https://github.com/railsgirls-jp/railsgirls.jp/pull/762/commits/1b13b407dea2b472ebda6632d31c17c55dbc0485

2023-12-05 13:35 UTC, thatblue commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +さらに、スポンサーLTとして、「フィヨルドブートキャンプ」様からの動画LT、そして今年のRuby Biz Prix大賞を受賞された「PIXIV」様からの現地LT（法被を身にまとったLTでした！）、さらに「Tokyo Dev」様は、Rail Girl Matsueのために松江に足を運んで発表してくださったことに感謝申し上げます。
ありがとうございます、修正を確認しました～

2023-12-05 13:36 UTC, thatblue commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +Rails Girls は、より多くの女性がプログラミングに親しみ、アイデアを形にできる技術を身に着けるきっかけ作りと手助けをするコミュニティです。2010年にフィンランドのヘルシンキにてリンダ・リウカス氏らによって設立された団体であり、今では世界各国で活動が行われています。
ご対応ありがとうございます！修正確認しました～

2023-12-05 13:41 UTC, thatblue approved these changes
修正ご対応ありがとうございました！
素敵なイベントになったようで良かったです、読んでいて私も楽しい気持ちになりました 😊

2023-12-06 04:13 UTC, ishikawa999 commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +そして仕組みが分かった第２回戦は戦略をチームで練ります。そして、２回目では、最も早く並び替えたチームから今回のスペシャルゲスト江森真由美氏からご提供いただいた本を景品をプレゼント。
> そして、早く並び替えを完了したチームから順に景品をプレゼント！
> 景品は『はじめてつくるWebアプリケーション 〜Ruby on Railsでプログラミングへの第一歩を踏み出そう』、『ユウと魔法のプログラミング・ノート』、『RubyとRailsの学習ガイド 2023』といった、RubyやRailsの勉強に役立つ素晴らしい本です。これらの本は、著者である江森真由美氏、鳥井雪氏、五十嵐邦明氏からご寄贈いただきました。心から感謝申し上げます！

のように書名があったほうが良いかもしれません...。今手元に環境がないので後からコミットを追加しようと思います

2023-12-06 09:34 UTC, ishikawa999 commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +そして仕組みが分かった第２回戦は戦略をチームで練ります。そして、２回目では、最も早く並び替えたチームから今回のスペシャルゲスト江森真由美氏からご提供いただいた本を景品をプレゼント。
https://github.com/railsgirls-jp/railsgirls.jp/pull/762/commits/e97c67120f6d4df0b75f46a34e03b82e0febe903
のようにしました

2023-12-13 22:17 UTC, emorima commented on _posts/blog/2023-11-11-railsgirls-matsue-5th.markdown
> +そして仕組みが分かった第２回戦は戦略をチームで練ります。そして、２回目では、最も早く並び替えたチームから今回のスペシャルゲスト江森真由美氏からご提供いただいた本を景品をプレゼント。
修正ありがとうございます！変更して頂いた内容でOKです！ 🙆 

対応頂いて、ありがとうございます～ ❤️

2023-12-13 22:18 UTC, emorima approved these changes
修正確認しました！ OKです ❤️

2023-12-14 08:54 UTC, merged

2023-12-14 08:54 UTC, thatblue commented
執筆ありがとうございました！マージしました〜

2023-12-14 09:22 UTC, ishikawa999 commented
@thatblue @emorima 
ご対応いただきありがとうございました！