Rails Girls Remote Pairing Tutorialを翻訳した
railsgirls-jp/railsgirls.jp pull request #772
Opened 2023-12-10 08:40 UTC by maimux2x

## やったこと
https://railsgirls.jp/remote
こちらのガイドを翻訳しました。

![FireShot Capture 051 - Rails Girls - Japanese - localhost](https://github.com/railsgirls-jp/railsgirls.jp/assets/76797372/b385e2ce-a618-470f-8db3-24a372ffe663)

最終段落の以下について

>  It would be a world that reflects that most common of sayings that you probably hear at meetings of your local Ruby/Rails meet-up: “MINSWAN” – Matz is nice, so we are nice! Let’s get started being nice to each other!

`“MINSWAN” – Matz is nice, so we are nice! ` を強調するために意図的に改行を入れています。

close #771

2023-12-13 08:41 UTC, urimaro requested changes
1か所、訳し漏れてしまった部分があるようなので「Request changes」としました
他は個人的な意見なので、スルーしても :ok_hand:です

2023-12-13 08:41 UTC, urimaro commented on _pages/remote-pairing-for-the-win.md
> +まず初めに、この話題を共有する動機はなんでしょうか？もしこのチュートリアルを読まれているなら、あなたはすでに[Rails Girls](http://railsgirls.com)の力を理解しているでしょう。もしまだ知らない場合は、いくつかの事実をお伝えしましょう。Rails Girlsは、Ruby on Railsを使用したウェブアプリケーション開発を女性に紹介する組織です。世界中の多くの女性
![imo](https://img.shields.io/badge/imo-green.svg)
> パワフルで感動的な経験

体験でも良いかもしれません

> .. they have support of other women who extended their privilege to them

この部分は日本語にするのが難しいですね
「『エンジニアという社会的地位』(= privilege)を使って献身的にサポートしてくれる」というニュアンスがあると思っています
"their privilege" を「特権」とすると「特別」な印象が強いかもしれないので意訳しても良いかもしれません
例えば…

- 自らの知識や立場を分かち合う女性たちからサポートが受けられることを…

2023-12-13 08:41 UTC, urimaro commented on _pages/remote-pairing-for-the-win.md
> +* オプションとして、あなたと友達のGoogleアカウントか、Skypeアカウント、もしくは他の手段でも良いですが、お互いの声を聞くことができるものが必要です。
![imo](https://img.shields.io/badge/imo-green.svg)
オプションなので「必要です」のくだりは必要なさそうです

- オプションとして、あなたと友達のGoogleアカウントか、Skypeアカウント、もしくは他の手段でも良いですが、お互いの声を聞くことができるもの

2023-12-13 08:41 UTC, urimaro commented on _pages/remote-pairing-for-the-win.md
> +4. ターミナルで共有したいディレクトリに`madeye`と入力しましょう。
![imo](https://img.shields.io/badge/imo-green.svg)

> .. ディレクトリに ..

「ディレクトリで」のほうが良いかもと思いました

2023-12-13 08:41 UTC, urimaro commented on _pages/remote-pairing-for-the-win.md
> +5. Madeyeがあなたのターミナルに、チームメイトと共有するためのURLを表示します。
![must](https://img.shields.io/badge/must-magenta.svg)
> .. and all of you can go there in your browser and edit code.

上記が抜けてしまっているようです

2023-12-13 08:41 UTC, urimaro commented on _pages/remote-pairing-for-the-win.md
> +もし、あなたがコーチングしている場合、あなたとコーチング対象の人は自分達のブラウザ画面の左側を見て、特定のディレクトリにあるあなたのアイコンを見ることができます。コーチング対象者がそのディレクトリをクリックすると、ファイルまたは別のディレクトリにおいても、再びあなたのアイコンが表示されます。コーチング対象者はコーチのアイコンを辿って編集したいファイルに移動し、コーチはコード内で対象者のカーソルを
![imo](https://img.shields.io/badge/imo-green.svg)
> コーチング対象者はコーチのアイコンを辿って編集したいファイルに移動し、コーチはコード内で対象者のカーソルを見ることができます

この文の「You」は、何を指しているのかわかりにくいですよね…
前の文同様、コーチングの対象者が操作している状況を説明するのであれば、文の後半を以下のように変えてみるのはいかがでしょうか？

- …移動し、コードの中にカーソルを見つけることができます
- …移動し、カーソルがあるコードを確認できます

※ あえて主語は訳しませんでした

2023-12-13 08:41 UTC, urimaro commented on _pages/remote-pairing-for-the-win.md
> +ガイドの作者は、Madeyeがペアプログラミングにとって最も優れたものだと信じています。ただし、このガイドは読者のみなさんへの贈り物であり、またペアプログラミングの世界への貢献であるため、Pair Programming Worldへの責任を怠らないように、以下のリンクを提供します。
![imo](https://img.shields.io/badge/imo-green.svg)
> ただし、このガイドは読者のみなさんへの贈り物であり、またペアプログラミングの世界への貢献であるため、Pair Programming Worldへの責任を怠らないように、以下のリンクを提供します。

想定外のところで `,` が入っていたり日本語にするのが難しいですよね
以下のような訳はいかがでしょうか

- ただし、このガイドは読者の皆さんはもちろん、あなたとペアを組むかもしれない人たちへの贈り物でもあります。
ですので、ペアプログラミングの世界への務めを怠らないよう、たくさんの選択肢が紹介されている以下のリンクを紹介します。

2023-12-13 08:41 UTC, urimaro commented on _pages/remote-pairing-for-the-win.md
> +あなたとペアプログラミングを行う仲間たちにとって最適な方法を見つけていただければ幸いです。
![imo](https://img.shields.io/badge/imo-green.svg)
> 最適な方法を見つけていただければ幸いです。

急にかしこまった文体になってしまったように感じました
以下のような感じはいかがでしょうか？

- 最適な方法が見つかれば幸いです

2023-12-13 08:41 UTC, urimaro commented on _pages/remote-pairing-for-the-win.md
> +さあ、お互いに親切であることを始めましょう！
![imo](https://img.shields.io/badge/imo-green.svg)
> 親切であることを始めましょう

ちょっと違和感を感じました
「親切になりましょう」とかどうでしょう

2023-12-17 06:21 UTC, maimux2x commented on _pages/remote-pairing-for-the-win.md
> +まず初めに、この話題を共有する動機はなんでしょうか？もしこのチュートリアルを読まれているなら、あなたはすでに[Rails Girls](http://railsgirls.com)の力を理解しているでしょう。もしまだ知らない場合は、いくつかの事実をお伝えしましょう。Rails Girlsは、Ruby on Railsを使用したウェブアプリケーション開発を女性に紹介する組織です。世界中の多くの女性
ありがとうございます！
「特権」だと少し言葉が強いな・・・と思っていたため、ご提案いただいた内容で修正しました✨

2023-12-17 06:22 UTC, maimux2x commented on _pages/remote-pairing-for-the-win.md
> +* オプションとして、あなたと友達のGoogleアカウントか、Skypeアカウント、もしくは他の手段でも良いですが、お互いの声を聞くことができるものが必要です。
> オプションとして、あなたと友達のGoogleアカウントか、Skypeアカウント、もしくは他の手段でも良いですが、お互いの声を聞くことができるものあると良いです。

にしてみました〜！

2023-12-17 06:24 UTC, maimux2x commented on _pages/remote-pairing-for-the-win.md
> +4. ターミナルで共有したいディレクトリに`madeye`と入力しましょう。
ディレクトリに入力する訳ではないため、「で」に修正しました！

2023-12-17 06:26 UTC, maimux2x commented on _pages/remote-pairing-for-the-win.md
> +5. Madeyeがあなたのターミナルに、チームメイトと共有するためのURLを表示します。
見落としていました🙇🏻‍♀️
訳文を追加します！

2023-12-17 06:28 UTC, maimux2x commented on _pages/remote-pairing-for-the-win.md
> +もし、あなたがコーチングしている場合、あなたとコーチング対象の人は自分達のブラウザ画面の左側を見て、特定のディレクトリにあるあなたのアイコンを見ることができます。コーチング対象者がそのディレクトリをクリックすると、ファイルまたは別のディレクトリにおいても、再びあなたのアイコンが表示されます。コーチング対象者はコーチのアイコンを辿って編集したいファイルに移動し、コーチはコード内で対象者のカーソルを
主語を訳さなくても意味が通るため、ご提案いただいた

> …移動し、コードの中にカーソルを見つけることができます

に修正しました✨

2023-12-17 06:32 UTC, maimux2x commented on _pages/remote-pairing-for-the-win.md
> +ガイドの作者は、Madeyeがペアプログラミングにとって最も優れたものだと信じています。ただし、このガイドは読者のみなさんへの贈り物であり、またペアプログラミングの世界への貢献であるため、Pair Programming Worldへの責任を怠らないように、以下のリンクを提供します。
ありがとうございます！！
なんと訳すか迷った部分でした・・・
ご提案いただいた内容に変更ことでメッセージが伝わると思い、修正いたしました！

2023-12-17 06:33 UTC, maimux2x commented on _pages/remote-pairing-for-the-win.md
> +あなたとペアプログラミングを行う仲間たちにとって最適な方法を見つけていただければ幸いです。
「幸いです」に引っ張られて固くなってしまいました😅
こちらも修正しました！

2023-12-17 06:34 UTC, maimux2x commented on _pages/remote-pairing-for-the-win.md
> +さあ、お互いに親切であることを始めましょう！
読み直して自分でも違和感を感じました😅
ありがとうございます！
修正しました✨

2023-12-17 16:07 UTC, urimaro approved these changes
対応ありがとうございます
1か所、確認をお願いします :pray:
修正したらmergeしてしまって 👌 です

2023-12-17 16:07 UTC, urimaro commented on _pages/remote-pairing-for-the-win.md
> +* オプションとして、あなたと友達のGoogleアカウントか、Skypeアカウント、もしくは他の手段でも良いですが、お互いの声を聞くことができるものあると良いです。
![nits](https://img.shields.io/badge/nits-orange.svg)

> ..できるものあると良いです。

「が」が抜けてしまっているようです

2023-12-18 13:27 UTC, maimux2x commented on _pages/remote-pairing-for-the-win.md
> +* オプションとして、あなたと友達のGoogleアカウントか、Skypeアカウント、もしくは他の手段でも良いですが、お互いの声を聞くことができるものあると良いです。
見落としていました・・・＞＜
気づいていただき、ありがとうございます🙏

2023-12-18 13:27 UTC, merged