Your guide to the Rails Girls Guide!を翻訳した
railsgirls-jp/railsgirls.jp pull request #775
Opened 2023-12-16 13:21 UTC by maimux2x

## やったこと
https://railsgirls.jp/guide-to-the-guide#1_create_the_application を翻訳しました。

close #773

2023-12-28 04:10 UTC, urimaro requested changes
翻訳してくださり、ありがとうございます！👏
内部の説明が含まれているので、伝わるように訳すのが難しかったと思います

---

たくさんコメントしてしまいましたが、![nits](https://img.shields.io/badge/nits-orange.svg)、![imo](https://img.shields.io/badge/imo-green.svg) は気になったところで、![must](https://img.shields.io/badge/must-magenta.svg) は直したほうが良いと思ったところです
気になり具合の程度は以下のとおりです
- ![must](https://img.shields.io/badge/must-magenta.svg) > ![nits](https://img.shields.io/badge/nits-orange.svg) > ![imo](https://img.shields.io/badge/imo-green.svg)

![must](https://img.shields.io/badge/must-magenta.svg) 以外は、対応する/しないは @maimux2x さんの判断に任せます:pray:

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +知っておきたいコマンド
![imo](https://img.shields.io/badge/imo-green.svg)
need なので「知っておくべき」でも良いかもしれません

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +モデルとマイグレーションをscaffoldで作成
![imo](https://img.shields.io/badge/imo-green.svg)
「,」で区切られているので、それぞれを並べるだけで良さそうです
リンク先でも、個別に説明されていました

- scaffold、モデル、マイグレーション

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +「Localhost」は具体的にはあなたのコンピュータ（「ローカルホスト」と呼ばれる）を指し、そこからサーバーが起動されます。ローカルホストは、開発者がアプリケーションをブラウザで確認し、開発中に機能をテストする手段を提供します。
![imo](https://img.shields.io/badge/imo-green.svg)

> （「ローカルホスト」と呼ばれる）

文字通りだと「ローカルホストとみなされる」かなと思いましたが、今の訳でも良さそうです

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +Railsでは、モデルはアプリケーション内のリソースの定義を表し、そのリソースがアプリケーションの他の部分とどのように相互作用すべきかを表します。ウェブサイトの性質に応じて、これらのリソースはusers、posts、groupsなどになります。モデルが生成されると、対応する*データベーステーブル*が作成されます。このデータベーステーブルには、モデルの指定された属性を表す情報が含まれています。例え
![imo](https://img.shields.io/badge/imo-green.svg)
> …どのように相互作用すべきかを…

scaffoldの説明で「interact」を「やりとり」としているので、そろえても良さそうに思いました
柔らかい表現にもなりますし

![nits](https://img.shields.io/badge/nits-orange.svg)
> …レコードが存在します

「will be」なので以下のような訳の方が良さそうに思いました

- そして、ユーザーが作成されるたびに、これらはテーブルの行になります
- そして、ユーザーが作成されるたびに、これらはレコードになります

「それぞれ」と「たびに」が重複しているように感じたので、1つにまとめています
わかりやすくするために「テーブルの」を補っても良いかなと思いました

![imo](https://img.shields.io/badge/imo-green.svg)
> これらのリソースはideasであり、モデルは「Idea」です。

ちょっとわかりにくいかもしれないなと思いました
少し意訳していますが、以下のような訳はどうでしょう？

- ideasがリソースに、「Idea」がモデルに当てはまります
- ideasがリソースに、「Idea」がモデルに該当します

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +Ideaモデルを作成するために、`scaffold`コマンドを使用します。このコマンドには単数系のモデル名（`idea`）と、モデルの属性に関するパラメータ（仕様）を含む引数があります。これは`idea`モデルが、コマンドで指定された属性`name`、`description`、および`picture`に対応するデータベース内のテーブルであることを意味します。また、`scaffold`コマンドは
![imo](https://img.shields.io/badge/imo-green.svg)
> …引数があります

「which includes」なので「引数を指定します」というのはどうでしょうか？

- このコマンドでは単数系のモデル名（`idea`）と、モデルの属性に関するパラメータ（仕様）を含む引数を指定します

1つの文にするとこんな感じでしょうか？

- Ideaモデルを作成するために、単数系のモデル名（`idea`）と、モデルの属性に関するパラメータ（仕様）を引数に指定して、`scaffold`コマンドを使います。

![imo](https://img.shields.io/badge/imo-green.svg)
> これは`idea`モデルが、コマンドで指定された属性`name`、`description`、および`picture`に対応するデータベース内のテーブルであることを意味します。

英文の言いたいことはわかるけれど日本語にしにくい文ですね
「corresponds to a table」なので、「correspond to」の対象を属性からテーブルに変えてみました
この訳文は参考程度で🙏

- これは`idea`モデルが、コマンドで指定した属性(`name`、`description`、および`picture`)の列/カラムを持つデータベーステーブルに対応することを意味します

理解の邪魔をしないよう属性名をカッコで囲ってみました
次の文の訳に合わせて「table in database」を「データベーステーブル」としてみました
前の段落で説明しているので「データベース」は省略しても良いかもしれません

![imo](https://img.shields.io/badge/imo-green.svg)
> 関係を確立する

ちょっと硬い感じがしました
「関連付ける」はどうでしょうか？
データベースの文脈だと「関連」という言葉が使われることが多いというのも提案した理由の1つです

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +`name:string description:text picture:string` - モデル（およびそれに関連するデータベーステーブル）が持つ属性のリストを提供します。 引数の中の`string`と`text`の部分は、各属性の性質を決定します。つまり、各説明は「text」である必要があり、例えば「integer」（または他の任意の情報の型）であってはいけません。
![imo](https://img.shields.io/badge/imo-green.svg)
> …各説明は「text」である必要があり、…

この「説明」の部分は「description」のままの方がわかりやすいかもしれません

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +Railsでは、アプリケーションのデータベースとやり取りするためのデフォルトのシステムは*Active Record*と呼ばれ、データの作成、保存、および検索するためのさまざまなメソッドを提供しています。データベースから情報を取得するにあたり、*Active Record*は異なるアプリケーションの部分間に関係を確立するために命名規則を使用します。
![nits](https://img.shields.io/badge/nits-orange.svg)
> …データの作成、保存、…

「データを」のほうが良さそうです

![imo](https://img.shields.io/badge/imo-green.svg)
> …関係を確立する…

日本語訳の62行目と同様です

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +- モデルは、慣例としてMixedCaseの規約を使用して命名され、常にテーブル名の単数形です。たとえば、テーブル名が「invoice\_items」の場合、モデル名は「InvoiceItem」になります。したがって、今回の場合、テーブル名は 「ideas」であり、モデルは「Idea」となります。
![nits](https://img.shields.io/badge/nits-orange.svg)
> 慣例として

「慣例」と「規約」が重複しているように感じました
Railsの文脈だと規約だけで良いかもしれません

![imo](https://img.shields.io/badge/imo-green.svg)
> the convention of unbroken MixedCase

もう少し説明してあげたほうがわかりやすいかもしれません
例えば「大文字小文字を混在させ、単語を連続させるという規約」など
(もっと良い表現がありそう😅)

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +既に説明したように、モデルは対応するデータベーステーブルのカラムで表される属性（プロパティ）を持つことができます。 Active Recordシステムでサポートされるためには、これらの属性は適切な型のリストに準拠している必要があります。
![imo](https://img.shields.io/badge/imo-green.svg)
> サポートされるためには、…準拠している…

ちょっと硬い感じがしたので「サポートを受けるには…従う…」とかどうでしょう

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +固定された精度で小数点を格納します。つまり、精度を指定することはできません（`:decimal`は精度が必要な数学演算に適していますが、`:float`は処理が速く、精度が二次的な場合に適しています）。
![nits](https://img.shields.io/badge/nits-orange.svg)
思わず改行してしまった感じでしょうか

> .. and is better in situations where speed is required and accuracy is secondary

以下のような感じでどうでしょうか

- `:float` のほうが処理が早いです。このため、正確さよりも速度が優先される場合に適しています。

「精度」だと、数学的な意味と一般的な意味を混同してしまいやすそうなので「正確さ」としました

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +- `:timestamp` - 時刻と日付の両方を格納します。`:timestamp`は`:datetime`とは異なり、異なる目的に役立ちますが、ここでは必要がないため詳しくは説明しません。
![imo](https://img.shields.io/badge/imo-green.svg)
> …異なり、異なる…

「異なる」が連続しないように「…異なるものであり、別の目的に…」のように別の言葉を使うのはどうでしょうか？

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +マイグレーションはデータベースの状態を変更します。`scaffold`コマンドを実行すると、コマンドに関連するデータベーステーブルへの指示が含まれたマイグレーションファイルが、アプリケーションの`db/migrate`フォルダに追加されます。例えば、`rails generate scaffold`コマンドを実行すると、ideasテーブルへの指示を含むマイグレーションが作成されます。他にも `r
![imo](https://img.shields.io/badge/imo-green.svg)
> マイグレーションが作成されます

前の文と合わせて「マイグレーションファイル」としても良いかもしれません

> 他にも `rails generate model` コマンドや

「他にも」を文末に持っていくと読みやすく感じかもしれないと思いました

- `rails generate model` コマンドや…コマンドなど、マイグレーションファイルを生成するコマンドが他にもあります

「マイグレーション」を「マイグレーションファイル」にしました

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +`rake db:migrate` コマンドはマイグレーションファイルの指示に従ってデータベースを更新します。このコマンドは 「migrating up」として知られており、あなたのIdeaモデルがデータベースに追加されることを保証します。コマンド `rake db:rollback` を使えば、マイグレーションを取り消す（「migrating down」）こともできます。
![imo](https://img.shields.io/badge/imo-green.svg)
> …指示に従って…

文字通りなら「仕様」かなと思いました
前の段落では `a migration file containing instructions` と表現していますし、意味は通じるので、このままでも良いと思います

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +HTMLとは、ハイパーテキスト・マークアップ・ランゲージ（HyperText Markup Language）の略で、Webブラウザで表示できるWebページやその他の情報を作成するための主要な言語です。HTMLはタグを使って記述され、角括弧はテキストベースのコンテンツを囲む2つのタグ（開始タグと終了タグ）で構成されます。対になるタグでは、開始タグと区別するために、終了タグも開始角括弧の後にスラッ
![must](https://img.shields.io/badge/must-magenta.svg)
> 角括弧は…

角括弧は `[]` のことを指すことが多いと思うので、山括弧のほうが良いと思います

> 構成されます。

「tend to」とありますし、終了タグがない場合もあるので、以下のような訳はいかがでしょう？

- 構成されることが多いです。

![nits](https://img.shields.io/badge/nits-orange.svg)
> …終了タグも開始角括弧の後に…

この「also」は、「前の文に書いてあることに加えて」という意味合いかなと思いました

- 終了タグは開始角括弧の後にスラッシュも付けます

![imo](https://img.shields.io/badge/imo-green.svg)
> 段落…は表示するテキストを囲むために、…

英文通りの薬ではありますが「囲むためにタグを使う」というのは違和感があるので、以下のように順番を変えても良さそうに思いました

- 段落…は、`<p>` のような開始タグおよび`</p>`のような終了タグを使って、表示するテキストを囲みます。

![imo](https://img.shields.io/badge/imo-green.svg)
> 閉じる必要がないが開かれたままの非対になるタグ

ちょっと表現が硬い感じがしたので、以下のような訳はどうでしょう？

- 開始しているけれど閉じる必要のないタグ

これまでの説明でタグはペアになることが多いと説明していますし、「that are opned ..」の説明と重複するので「Unpaired」は訳さなくても良いかなと判断しました

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +ERBは、Rubyが提供するシステムで、JavascriptやHTMLなど他の言語で書かれたファイルに純粋なRubyコードを挿入することができます。Rubyコードは特定の角括弧（`<%`および`%>`）内に含まれており、システムにその内容を実行するように指示します。角括弧の前に`=`記号が付随している場合（`<%=`および`%>`）、その内容が実行されてページ上にレンダリングされます。
![nits](https://img.shields.io/badge/nits-orange.svg)
> 角括弧の前に…

「前に」は不要かなと思いました
ちょっと表現が硬い感じがしたので、以下のような訳はどうでしょう？

- 角括弧に`=`が付いている場合（`<%=`および`%>`）、角括弧に囲まれた内容が実行され、ページに表示されます。

「その内容」の意味を補ってみました
また、レンダリングは意味がわからない人もいるかも知れないと思ったので日本語にしてみました

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +例えば、アプリケーションに25のアクティブなideasがあった場合、コードは次のようになります。
![nits](https://img.shields.io/badge/nits-orange.svg)
> …ideasがあった場合、…

この「ideas」はアプリを操作して登録したデータだと思うので、日本語にして良いと思います
＜アイデア、アイディア

次の行も同様ですが、アプリを多言語化していないのであれば英語のままだと思うので、次の行は「まったく翻訳しない」ほうが良いかもしれません

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +> 現在アクティブなideasは25個あります。
![must](https://img.shields.io/badge/must-magenta.svg)
レンダリングした結果なので、L156と同じ表現になるんじゃないかと思いました

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +CSS (Cascading Style Sheets)は「マークアップ言語」で書かれたページのフォーマットを表現するために利用される言語です。すなわち、テキストを処理し、定義し、所定の書式コードで表示するための言語でプレーンテキストとは区別されます。CSSの最も一般的な用途はHTMLとの併用です。
![imo](https://img.shields.io/badge/imo-green.svg)
> …フォーマットを表現するために…

フォーマットだとイメージできない人もいるかも知れないと思いました
書式、体裁、見た目などはどうでしょう？
また、「表現」を記述に変えても良いかもしれません
(記述は硬い感じですが)

![imo](https://img.shields.io/badge/imo-green.svg)
> …所定の書式コードで表示するための言語でプレーンテキストとは区別されます

ちょっとイメージしにくいかもしれないと思いました
また、「e.g. tags」が抜けてしまっているようです

- …タグのように決められた書式で表示するための言語で、普通のテキストとは区別されます

あまり効果がないかも…

![imo](https://img.shields.io/badge/imo-green.svg)
> CSSの最も一般的な用途はHTMLとの併用です。

「併用するために使われる」と読めてしまうかもしれないと思いました
こんな感じはどうでしょうか

- CSSは、HTMLと組み合わせて使われることが最も多いです
- CSSは、HTMLと組み合わせて使われることが一般的です
    あえて「most」は訳しませんでした

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +CSS内で適用されたのは、
![imo](https://img.shields.io/badge/imo-green.svg)
この後は箇条書きになっているので、文にしてしまうのはどうでしょうか？

- CSSの中で適用されたのは以下のとおりです
- CSS内では以下が適用されています

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +`{ padding-top: 100px; }` - この部分は宣言です。各宣言は、変更したいスタイル属性 (`padding-top`)と関連する値(`100px`)をプロパティとして持ちます。宣言は常にセミコロンで終わり、宣言グループは常に中括弧で囲われています。
![imo](https://img.shields.io/badge/imo-green.svg)
> 中括弧で囲われています

確かに「curly bracket」は中括弧とも呼ばれていますが、名前からはイメージしにくいので「波括弧」をという言葉を使うのはどうでしょうか？

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +各Railsアプリケーションには、viewsディレクトリのlayoutsフォルダにある`application.html.erb`というデフォルトのレイアウトファイルがあります。このファイルを使用して、アプリケーション内のすべてページに対してデフォルトフォーマットを作成することができます。
![imo](https://img.shields.io/badge/imo-green.svg)
> layoutsフォルダにある

文末の「あります」と重複してしまうので、「ある」は削ったほうが自然かなと思いました

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +上記のコードでは、`link rel`(link relation)は`href` (hypertext reference)属性がコンテンツを要求するURLの性質を定義しています。この引数は、要求された外部ソースがスタイルシートであり、Webブラウザがページを適切に表示するために、このファイルを取得する必要があることを示しています。
![nits](https://img.shields.io/badge/nits-orange.svg)
`link rel`の後の半角スペースは削除されていますが、`href`の後の半角スペースは削除されていないようです

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +このコードの場合は「application」、つまり`application.css`のソースに対するスタイルシートリンクタグを返します。これは、application.css で実装したスタイルがアプリケーションのさまざまなページに適用されることを意味します。
![imo](https://img.shields.io/badge/imo-green.svg)
> 「application」、つまり`application.css`のソース

`application.css` に「ソース」があると理解してしまうかもしれないと思いました
`application.css` は「the source」の例だと思うので、以下のような訳はどうでしょう？

- このコードは指定されたソース、今回の場合「application」、つまり`application.css`に対するスタイルシートリンクタグを返します。

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +- *containerクラス*は、divタグ内の全てにスタイリングを追加します。
![imo](https://img.shields.io/badge/imo-green.svg)
> …、divタグ内の全てにスタイリング…

「全て」が何なのかわかりにくいので「の要素」と補ってみるのもありかなと思いました
また、日本語としては「スタイル」のほうが良さそうに思いました

思い過ごしかもしれませんが、「このdiv」としてほうが、より実態を表せるかもしれません
「この」がないと、「class="container"」でないdivにも追加されると思ってしまうかもしれないと思ったのでした

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +- `<%= yield %>`引数は、各ページに対して固有のコンテンツを`div`に挿入する役割を担います。つまり、ページごとにコンテンツが異なっていても、アプリケーション全体のレイアウトは一貫しているということです。
![imo](https://img.shields.io/badge/imo-green.svg)
> …`div`に挿入する…

「the container `div`」とあるので「入れ物であるdiv」と補うと良いかもしれません
divコンテナを表していると思っていますが、コンテナについて説明されていないので「入れ物」としました

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +Rubyを含む多くのプログラミング言語は幅広いライブラリを使用しています。Rubyの場合、これらのライブラリのほとんどは*gem*と呼ばれる自己完結型パッケージの形でリリースされていて、そのパッケージにはライブラリをインストールして実装するために必要なすべての情報が含まれています。これらのgemはアプリケーションの`Gemfile`に含まれていて、このファイルを見てみると、最初のRailsアプリ
![imo](https://img.shields.io/badge/imo-green.svg)
> …gemがいくつか含まれていること…

「came」と過去形になっているので以下のような訳はどうでしょうか

- …機能するようにgemがいくつか同梱されたこと…
- …アプリケーションを正しく機能させるためにgemがいくつか同梱されたこと…

「含まれたこと」だと不自然な感じがしたので変えてみました

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +Gemはソフトウェア開発の原則であるDRY (Don’t Repeat Yourself)に従って、開発者のコードを簡素化し、コードの重複を防ぐことに役立ちます。Gemは特定の問題を解決したり、特定の機能を追加したり、特定の要件に対処したりします。これは、他の開発者が同じようなシナリオに遭遇した際に、新たなコードを書く代わりに予め書かれたコードを含むGemをインストールすることができるということ
"meaning that should another developer encounter a similar scenario" の should の使い方は知りませんでした…
＜仮定法過去におけるshouldの倒置
むずかしいですね

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +RailsフレームワークとRuby言語の両方は、オープンソースソフトウェアの一例です。オープンソースソフトウェアは普遍的なアクセスを保証するライセンスのもとでリリースされていて、誰でもソフトウェアを変更、研究、配布する権利があります。ソースコードを公開することで、お互いの開発から恩恵を受けるプログラマーたちの、多様で、再帰的で、協力的な、その結果として進化を続けるプログラマーのコミュニティが形成
![imo](https://img.shields.io/badge/imo-green.svg)
> 普遍的なアクセスを保証するライセンス

正確な訳だと思いますが「普遍的なアクセス」が伝わらないかもしれないと思いました
参考までに別の案を書いておきます

- 誰もがアクセスできることを保証するライセンス

![imo](https://img.shields.io/badge/imo-green.svg)
> 再帰的で

コミュニティの説明なので、この文脈では「思慮深い」という意味かなと思いました

![imo](https://img.shields.io/badge/imo-green.svg)
「Making the source code..」の文、日本語にするの難しいですね😅

> …コミュニティが形成され、

この文の場合、ココで切らないほうが良いかも？と思ったので、参考までに「enables」が「establishment」に、「establishment」が「community」に、「programmers」以下が「community」にかかるものとして訳してみました

- ソースコードを公開することで、お互いの開発から恩恵を受けるプログラマーたちによる、多様で、思慮深く、協力的であり、その結果、進化し続ける双方向的なコミュニティを形成することができます。

原文と訳の対応は以下のような感じです

- Making the source code accessible
    ソースコードを公開することで、
- enables the establishment
    形成することができます
- a diverse, reflexive, collaborative and consequently ever-evolving interactive community
    多様で、思慮深く、協力的であり、その結果、進化し続け、お互いが影響し合うコミュニティ
- of programmers who all benefit from each others’ developments.
    お互いの開発から恩恵を受けるプログラマーたちによる

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +`app/views/ideas/_form.html.erb`ファイルにはideasの編集と作成に使用されるフォーム(`edit.html.erb`と`new.html.erb`ビュー)の見た目と雰囲気を定めるHTMLコードが含まれています。パーシャルとは、複数の場所で再利用できるHTMLとRubyのコードのスニペットです。既存のideasを編集するフォームと新規にideasを作成するフォーム
![imo](https://img.shields.io/badge/imo-green.svg)
> …見た目と雰囲気を…

「look and feel」は「見た目」だけでも良さそうに思いました

![nits](https://img.shields.io/badge/nits-orange.svg)
> …Railsにパーシャルな`_form.html.erb` を…

Railsの文脈であれば「partial」は名詞として扱って良さそうに思いました
＜部分テンプレートのことをパーシャルと呼んでいる
この場合、「the partial」と「`_form_html.erb`」は同じもの(同格？)と考えて、以下のように訳すのはどうでしょう？

- パーシャルである `_form_html.erb`

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +`<%= f.file_field :picture %>`で実装しているコードは、Railsに対してフォームにファイル添付を作成し、送信された情報をideasデータベーステーブルの「idea」の「picture」属性にマッピングするように指示しています。コードを`<%= f.text_field :picture %>`から`<%= f.file_field :picture %>`に変更した
![imo](https://img.shields.io/badge/imo-green.svg)
> `<%= f.file_field :picture %>`で実装しているコードは

2つ上の行同様、「The code」と「`<%= … $>`」を同じものとして訳すと自然な感じになるかなと思いました

- 実装しているコード `<%= f.file_field :picture %>` は
- 実装したコード `<%= f.file_field :picture %>` は
- コード `<%= f.file_field :picture %>` は

コードを説明している他の部分についても同様です

![imo](https://img.shields.io/badge/imo-green.svg)
> フォームにファイル添付を作成し、

少し補うとわかりやすくなるかなと思いました

- フォームにファイル添付用の入力欄を作成し、

![imo](https://img.shields.io/badge/imo-green.svg)
> マッピングするように

わかってもらえる気もしますが「対応させるように」のように日本語に直したほうがわかりやすいかもしれません

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +`<%= @idea.picture %>`コードの中の`@idea`は*インスタンス変数*です。インスタンス変数には@記号がつき、それらが参照されるビューに対応するコントローラーアクションで定義されます。今回実装しているコードでは`@idea`は`Ideas`コントローラの「show」
「For the purposes of the code we are implementing, 」を「今回実装しているコードでは」と訳しているの、良いですね
僕では思いつけない表現だと思いました

![imo](https://img.shields.io/badge/imo-green.svg)
> インスタンス変数には@記号がつき、

「prefixed with」とあるので「…には先頭に@記号が…」としても良さそうです
(本文中にコードが書いてあるからわかる気もしますが)

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +`@idea`変数に続くコード(`.picture`)は、Railsに対してリソース（idea）の「picture」属性にアクセスするように指示しています。 `<%= @idea.picture %>`コードを`<%= image_tag(@idea.picture_url...)`に置き換えることによって、Rubyの`image_tag`*ヘルパー*を使用するようになります。これはHTMLの`
![imo](https://img.shields.io/badge/imo-green.svg)
> ただし、デフォルトではアップロードされた…

くどいかもしれませんが、主語「`image_tag` ヘルパー」を補ったほうがわかりやすいかもしれないと思いました

![imo](https://img.shields.io/badge/imo-green.svg)
> (`@idea.picture_url`)

挿入位置は「コードブロック」の後が良さそうに思いました

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +あなたが実装しているこのコードブロックの中で、各画像のデフォルト幅も設定できることにお気づきでしょう(`:width => 600`)。最後の行にある`if @idea.picture.present?`コードは、関連するデータベースのテーブルをチェックしてコードをレンダリングする前に画像が存在するかを確認するようにRailsに指示をしています。
![nits](https://img.shields.io/badge/nits-orange.svg)
> コードをレンダリングする前に

「underneath」とあるので、レンダリングする対象を示すために「この下にあるコードを」とすると良さそうです

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +機能的なRailsアプリケーションでは、適切なレスポンスを返すためにブラウザから受信したリクエストを変換するシステムが組み込まれています。このシステムは*ルーティング*と呼ばれます。ブラウザからのリクエストは特定のHTTPメソッドとして解釈されます。HTTP（ハイパーテキスト・トランスファー・プロトコル）とは、情報（通常、Webページや、ハイパーリンクを持つテキストで構成されたWebページ・コン
![imo](https://img.shields.io/badge/imo-green.svg)
> これらのアクションは、関連するコントローラー…で定義され、各モデルにはそれに関連するコントローラー…

「関連するコントローラー」が重複しているので、以下のような訳にすると読みやすいかもしれません

- このため、各モデルに対して、関連する7つのアクションがコントローラー(例えば `ideas_controller.rb`)で定義されることになります
- このため、各モデルに対して、関連するコントローラー(例えば `ideas_controller.rb`)で7つのアクションが定義されることになります

前の文で「アクションが定義される」と説明されていることを考えて「定義されることになる」という言い回しにしてみました

![nits](https://img.shields.io/badge/nits-orange.svg)
> レンダリングするための適切なレスポンス(メソッド)

「is most likely to」とあるので、以下のような訳はどうでしょうか

- これらのアクションは、対応するビュー（例：`ideas/index.html.erb`）をレンダリングすることが最も多い適切なレスポンス（メソッド）を指定します。

![imo](https://img.shields.io/badge/imo-green.svg)
「(メソッド)」だけだと分かりづらいかもしれないので、「(メソッドの1つ)」「(というメソッド)」と補足すると良さそうです

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +			<td>HTTPメソッド</td>
コード部分全般で気になることなのですが、各ガイドの実装とそろっているのでしょうか
そろっていない箇所を見つけたわけではなく、気になったのでコメントしました

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +`ideas_controller.rb`を見ると、これらのアクションと関連する振る舞い、および各アクションに対応するHTTPメソッドが確認できます。
![nits](https://img.shields.io/badge/nits-orange.svg)
差分がわかりやすくなるように空行を追加しておいてください🙏

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +（このコードを今の段階で明確に深掘りするのは難しいですが、Railsを使い続けていれば時間の経過とともに理解が深まるでしょう。）
「深堀りする」と訳すの良いですね👍

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +上記のshowアクションの定義では、Railsは`respond_to`ヘルパーメソッドを使って、それに続く*ブロック*のコード(`do...end`構文で囲まれたコード)を実行するよう指示しています。このコードには、リクエストの性質に応じて2つの異なるフォーマットオプションが含まれています。ブラウザがHTMLを要求した場合は、このコントローラーアクションに対応するビュー (`show.html
![imo](https://img.shields.io/badge/imo-green.svg)
> ビューはバイパスされ、

バイパスの意味をイメージできないかもしれないので、「無視され」「考慮されず」のほうが良いかもしれません

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +このように、URLリクエストはHTTPメソッドに変換され、それがコントローラーアクションにマッピングされ、Railsにビューを返すように指示されます。
![nits](https://img.shields.io/badge/nits-orange.svg)
> Railsにビューを返すように指示されます

文を分けたためか、この部分の主語が「HTTPメソッド」であるかのように感じました
以下のような訳はどうでしょうか？

- このように、URLリクエストはHTTPメソッドに変換され、Railsにビューを返すよう伝えるコントローラーのアクションに関連づけられます

2023-12-28 04:10 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +`root :to => redirect('/ideas')`コードを`config.rb`に挿入すると、アプリケーションのデフォルトルートを[http://localhost:3000/ideas](http://localhost:3000/ideas) にするよう Rails に指示します （このアプリケーションはまだ開発中なので、ドメインとして Localhost が使用されていること
![imo](https://img.shields.io/badge/imo-green.svg)
> …パス(`/ideas`)が含まれており、これにより…

文を分けたためか、「デフォルトのパスを指定したからindexアクションにマッピングされた」ように感じました
「パス(`/ideas')」を修飾するような表現に変えるのはどうでしょうか？

- このURLにはideasコントローラーの「index」アクションに対応したパス(`/ideas`)がデフォルトで含まれており、関連するビュー(`index.html.erb`)がレンダリングされます。

![imo](https://img.shields.io/badge/imo-green.svg)
> …`public/index.html` ファイルを削除します

読者に通じるかわかりませんが「`rm`」が抜けているようです

- …`public/index.html` ファイルを削除(removeの略語 `rm`)します

2024-01-06 11:59 UTC, maimux2x commented on _pages/guide-to-the-guide.md
> +- モデルは、慣例としてMixedCaseの規約を使用して命名され、常にテーブル名の単数形です。たとえば、テーブル名が「invoice\_items」の場合、モデル名は「InvoiceItem」になります。したがって、今回の場合、テーブル名は 「ideas」であり、モデルは「Idea」となります。
MixedCaseの後に括弧で説明を追加するように修正しています。

> モデルは、MixedCase(各単語の先頭が大文字で表記される)の規約を使用して命名され、常にテーブル名の単数形です。たとえば、テーブル名が「invoice\_items」の場合、モデル名は「InvoiceItem」になります。

全体の修正が完了した際に時間を置いて適切か見直してみます！

2024-01-06 12:02 UTC, maimux2x commented on _pages/guide-to-the-guide.md
> +固定された精度で小数点を格納します。つまり、精度を指定することはできません（`:decimal`は精度が必要な数学演算に適していますが、`:float`は処理が速く、精度が二次的な場合に適しています）。
間違えて改行を入れてますね😅

2024-01-06 12:21 UTC, maimux2x commented on _pages/guide-to-the-guide.md
> +> 現在アクティブなideasは25個あります。
これはまずい修正でした・・・ありがとうございます！！

2024-01-13 11:52 UTC, maimux2x commented on _pages/guide-to-the-guide.md
> +			<td>HTTPメソッド</td>
https://railsgirls.jp/app
こちらのガイドで作成するアプリの詳細な説明をしていると認識しています。

2024-01-13 12:43 UTC, maimux2x commented on _pages/guide-to-the-guide.md
> +例えば、アプリケーションに25のアクティブなideasがあった場合、コードは次のようになります。
こちらその通りだなと思ったのですが、この部分だけを見ると英語表記が残っていると認識してしまう可能性があるかなと思い、ファイルの該当箇所に捕捉コメントを入れるようにしました。

```
<!-- Rails Girlsガイドでは多言語対応について解説されていないため、英語表記の例のままにしています -->
```

2024-01-13 12:44 UTC, maimux2x commented on _pages/guide-to-the-guide.md
> +> 現在アクティブなideasは25個あります。
こちらは英語表記の例に戻しました

2024-01-13 13:09 UTC, maimux2x commented
@urimaro 
レビューをいただいてから間が空いてしまい、すみません🙇🏻‍♀️
内容を確認し、修正を反映いたしました。
改めてご確認をいただけると幸いです。

2024-01-21 06:08 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +- モデルは、慣例としてMixedCaseの規約を使用して命名され、常にテーブル名の単数形です。たとえば、テーブル名が「invoice\_items」の場合、モデル名は「InvoiceItem」になります。したがって、今回の場合、テーブル名は 「ideas」であり、モデルは「Idea」となります。
良い説明だと思います！ :+1:

2024-01-21 06:20 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +例えば、アプリケーションに25のアクティブなideasがあった場合、コードは次のようになります。
いいですね！ 👏 :
まさに @t-wada さんの「コードコメントには Why notを書こう」ですね！
https://x.com/t_wada/status/904916106153828352?s=20

2024-01-21 06:24 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +ERBは、Rubyが提供するシステムで、JavascriptやHTMLなど他の言語で書かれたファイルに純粋なRubyコードを挿入することができます。Rubyコードは特定の角括弧（`<%`および`%>`）内に含まれており、システムにその内容を実行するように指示します。角括弧の前に`=`記号が付随している場合（`<%=`および`%>`）、その内容が実行されてページ上にレンダリングされます。
角括弧を山括弧に直していただいて、ありがとうございます ❤️

2024-01-21 07:35 UTC, urimaro requested changes
@maimux2x 
確認に時間がかかってしまってすみません :bow:
1つ1つ丁寧に対応していただいて、ありがとうございます
更新された部分のみ確認しました
今までのコメントでわからないこと、気になることがあれば、後からでも構わないので遠慮なく質問してください :pray:

---

以下のコメント、素晴らしいと思いました

`<!-- Rails Girlsガイドでは多言語対応について解説されていないため、英語表記の例のままにしています -->`

まさに t-wada さんの「コードコメントには Why notを書こう」ですね！
https://x.com/t_wada/status/904916106153828352?s=20

---

改行してしまっている箇所を見つけたので、コメントしました
確認をお願いします :pray:

2024-01-21 07:35 UTC, urimaro commented on _pages/guide-to-the-guide.md
> +アクションで`@idea = Idea.find(params[:id])`のように定義されています。これにより、`show.html.erb`ビューで使用できるようになります。異なるコントローラーのアクション（例えばindexやnew）では異なる定義が可能です。コード`@idea = Idea.find(params[:id])`は、Railsの`find`メソッドを使ってデータベースから特定
![nits](https://img.shields.io/badge/nits-orange.svg)

改行してしまっているようです

2024-01-22 13:00 UTC, merged

2024-01-22 13:07 UTC, maimux2x commented
@urimaro 
こちらこそ毎回丁寧にレビューいただき、ありがとうございました🙏✨