「GitHubに自分のアプリをPushする」に main ブランチの注意事項を追加する
railsgirls-jp/railsgirls.jp pull request #798
Opened 2024-03-09 05:39 UTC by eitoball

本家では

```
_Your app's branch name may be different, like `main`. Change the "master" argument to the branch name listed in `git branch`. Your current branch is indicated with the `*` symbol at the start of the line._
```

となっている部分を追加します。

2024-03-15 08:46 UTC, urimaro requested changes
追加の翻訳、ありがとうございます！
コメントしましたので、ご確認ください :pray:

2024-03-15 08:46 UTC, urimaro commented on _pages/github.md
> +_アプリのブランチ名は `main` のように異なる場合があります。 "master" の引数を `git branch` にリストされているブランチ名に変更します。 現在のブランチは、行の先頭にある `*` 記号で示されます。_
![imo](https://img.shields.io/badge/imo-green.svg)
> "master" の引数を…

`master` というコマンドがあり、その引数について説明しているように解釈してしまうカモしれないと思いました
「引数 "master" を」のように "master" が引数であることがわかりやすい表現にすると良いかもしれません

![imo](https://img.shields.io/badge/imo-green.svg)
> …行の先頭にある `*` 記号で示されます

少し表現に違和感を感じました
以下のような表現はいかがでしょうか？

- 行の先頭に `*` 記号がつけられて表示されます

シンプルに「行の先頭に `*` 記号が表示されます」としてしまっても良いかもしれません

2024-03-15 13:51 UTC, eitoball commented on _pages/github.md
> +_アプリのブランチ名は `main` のように異なる場合があります。 "master" の引数を `git branch` にリストされているブランチ名に変更します。 現在のブランチは、行の先頭にある `*` 記号で示されます。_
ありがとうございます。いただいた提案のように変更しました。

2024-03-19 07:43 UTC, urimaro commented on _pages/github.md
> +_アプリのブランチ名は `main` のように異なる場合があります。 "master" の引数を `git branch` にリストされているブランチ名に変更します。 現在のブランチは、行の先頭にある `*` 記号で示されます。_
ありがとうございます！

2024-03-19 07:43 UTC, urimaro approved these changes
LGTM 👍 です！

2024-03-19 07:43 UTC, merged