Add Nagasaki 2nd
railsgirls-jp/railsgirls.jp pull request #825
Opened 2024-12-07 06:28 UTC by obregonia1

2024-12-15 01:38 UTC, siroemk commented on events/index.html
> +    <h3>Rails Girls Nagasaki 2nd<small>2025/02/14〜2025/04/15</small></h3>
`2025/02/14〜2025/02/15`ですかね👀

2024-12-15 08:49 UTC, obregonia1 commented on events/index.html
> +    <h3>Rails Girls Nagasaki 2nd<small>2025/02/14〜2025/04/15</small></h3>
[Fix date](https://github.com/railsgirls-jp/railsgirls.jp/pull/825/commits/c3b5d0533f281f3a7eb4c381e2bf4954fb2ac5f4)
ありがとうございます！こちらで修正しました🙏

2024-12-19 15:12 UTC, emorima requested changes

2024-12-19 15:12 UTC, emorima commented on index.html
> +    <a href="https://railsgirls.com/nagasaki_2nd.html">Rails Girls Nagasaki 2nd</a>
ここは、events.html と同じように、ロゴ画像付きで表示させて欲しいです。

```suggestion
    <a href="https://railsgirls.com/nagasaki_2nd.html" class="span4 event" style="background:url(/images/railsgirls-sq.png) center -20px  / 60% no-repeat;">
      <h3>Rails Girls Nagasaki 2nd<small>2025/02/14〜2025/02/15</small></h3>
    </a>                                                                                                                                          
```

2024-12-21 00:21 UTC, obregonia1 commented
@emorima 
ありがとうございます！コミットしました🙆‍♂️
![image](https://github.com/user-attachments/assets/32d58b4d-7b2d-48e2-b767-fea5f6792523)

2024-12-21 00:48 UTC, emorima approved these changes

2024-12-21 00:49 UTC, merged